INSERT INTO Champions (ChampionName, Grade)
VALUES
    ('Aatrox', 'Not S'),
    ('Ahri', 'S'),
    ('Akali', 'Not S'),
    ('Akshan', 'Not S'),
    ('Alistar', 'Not S'),
    ('Ambessa', 'Not S'),
    ('Amumu', 'S'),
    ('Anivia', 'S'),
    ('Annie', 'S'),
    ('Aphelios', 'S'),
    ('Ashe', 'S'),
    ('Aurelion Sol', 'S'),
    ('Aurora', 'Not S'),
    ('Azir', 'S'),
    ('Bard', 'Not S'),
    ('Bel''Veth', 'Not S'),
    ('Blitzcrank', 'S'),
    ('Brand', 'S'),
    ('Braum', 'S'),
    ('Briar', 'Not S'),
    ('Caitlyn', 'S'),
    ('Camille', 'Not S'),
    ('Cassiopeia', 'S'),
    ('Cho''Gath', 'S'),
    ('Corki', 'Not S'),
    ('Darius', 'Not S'),
    ('Diana', 'S'),
    ('Dr. Mundo', 'S'),
    ('Draven', 'S'),
    ('Ekko', 'S'),
    ('Elise', 'S'),
    ('Evelynn', 'Not S'),
    ('Ezreal', 'S'),
    ('Fiddlesticks', 'S'),
    ('Fiora', 'Not S'),
    ('Fizz', 'S'),
    ('Galio', 'S'),
    ('Gangplank', 'S'),
    ('Garen', 'S'),
    ('Gnar', 'Not S'),
    ('Gragas', 'S'),
    ('Graves', 'S'),
    ('Gwen', 'S'),
    ('Hecarim', 'S'),
    ('Heimerdinger', 'S'),
    ('Hwei', 'Not S'),
    ('Illaoi', 'S'),
    ('Irelia', 'Not S'),
    ('Ivern', 'Not S'),
    ('Janna', 'Not S'),
    ('Jarvan IV', 'Not S'),
    ('Jax', 'Not S'),
    ('Jayce', 'S'),
    ('Jhin', 'S'),
    ('Jinx', 'S'),
    ('K''Sante', 'Not S'),
    ('Kai''Sa', 'Not S'),
    ('Kalista', 'Not S'),
    ('Karma', 'S'),
    ('Karthus', 'Not S'),
    ('Kassadin', 'Not S'),
    ('Katarina', 'Not S'),
    ('Kayle', 'S'),
    ('Kayn', 'Not S'),
    ('Kennen', 'S'),
    ('Kha''Zix', 'Not S'),
    ('Kindred', 'S'),
    ('Kled', 'Not S'),
    ('Kog''Maw', 'S'),
    ('LeBlanc', 'Not S'),
    ('Lee Sin', 'Not S'),
    ('Leona', 'S'),
    ('Lillia', 'S'),
    ('Lissandra', 'S'),
    ('Lucian', 'Not S'),
    ('Lulu', 'Not S'),
    ('Lux', 'S'),
    ('Malphite', 'S'),
    ('Malzahar', 'S'),
    ('Maokai', 'Not S'),
    ('Master Yi', 'Not S'),
    ('Mel', 'S'),
    ('Milio', 'Not S'),
    ('Miss Fortune', 'S'),
    ('Wukong', 'Not S'),
    ('Mordekaiser', 'S'),
    ('Morgana', 'S'),
    ('Naafiri', 'S'),
    ('Nami', 'S'),
    ('Nasus', 'Not S'),
    ('Nautilus', 'S'),
    ('Neeko', 'Not S'),
    ('Nidalee', 'S'),
    ('Nilah', 'S'),
    ('Nocturne', 'S'),
    ('Nunu & Willump', 'S'),
    ('Olaf', 'S'),
    ('Orianna', 'S'),
    ('Ornn', 'Not S'),
    ('Pantheon', 'Not S'),
    ('Poppy', 'Not S'),
    ('Pyke', 'S'),
    ('Qiyana', 'Not S'),
    ('Quinn', 'S'),
    ('Rakan', 'S'),
    ('Rammus', 'Not S'),
    ('Rek''Sai', 'Not S'),
    ('Rell', 'S'),
    ('Renata Glasc', 'Not S'),
    ('Renekton', 'S'),
    ('Rengar', 'S'),
    ('Riven', 'Not S'),
    ('Rumble', 'S'),
    ('Ryze', 'Not S'),
    ('Samira', 'S'),
    ('Sejuani', 'Not S'),
    ('Senna', 'Not S'),
    ('Seraphine', 'Not S'),
    ('Sett', 'S'),
    ('Shaco', 'Not S'),
    ('Shen', 'Not S'),
    ('Shyvana', 'Not S'),
    ('Singed', 'S'),
    ('Sion', 'S'),
    ('Sivir', 'S'),
    ('Skarner', 'Not S'),
    ('Smolder', 'Not S'),
    ('Sona', 'Not S'),
    ('Soraka', 'S'),
    ('Swain', 'S'),
    ('Sylas', 'Not S'),
    ('Syndra', 'Not S'),
    ('Tahm Kench', 'S'),
    ('Taliyah', 'S'),
    ('Talon', 'S'),
    ('Taric', 'Not S'),
    ('Teemo', 'S'),
    ('Thresh', 'Not S'),
    ('Tristana', 'Not S'),
    ('Trundle', 'Not S'),
    ('Tryndamere', 'Not S'),
    ('Twisted Fate', 'S'),
    ('Twitch', 'Not S'),
    ('Udyr', 'Not S'),
    ('Urgot', 'S'),
    ('Varus', 'S'),
    ('Vayne', 'Not S'),
    ('Veigar', 'S'),
    ('Vel''Koz', 'S'),
    ('Vex', 'S'),
    ('Vi', 'S'),
    ('Viego', 'Not S'),
    ('Viktor', 'S'),
    ('Vladimir', 'S'),
    ('Volibear', 'S'),
    ('Warwick', 'Not S'),
    ('Xayah', 'Not S'),
    ('Xerath', 'S'),
    ('Xin Zhao', 'S'),
    ('Yasuo', 'S'),
    ('Yone', 'S'),
    ('Yorick', 'Not S'),
    ('Yunara', 'S'),
    ('Yuumi', 'S'),
    ('Zaahen', 'Not S'),
    ('Zac', 'S'),
    ('Zed', 'Not S'),
    ('Zeri', 'S'),
    ('Ziggs', 'S'),
    ('Zilean', 'S'),
    ('Zoe', 'Not S'),
    ('Zyra', 'Not S'),
    ('Locke', 'Not S')
  ;
