INSERT INTO Encounters (Area, Pokemon, EncounterResult, Nickname, LevelMet, Method, Notes, CurrentEvolution, IsAlive)
VALUES
    (N'Route 201', N'Chimchar', N'caught', N'Krom', 5, N'Gift', N'Starter, Ability: Iron Fist', N'Infernape', N'Yes'),
    (N'Lake Verity', N'Azurill', N'caught', N'Maliana', 5, N'First encounter', N'Ability: Huge Power', N'Azumarill', N'Yes'),
    (N'Route 201', N'Bidoof', N'caught', N'Bingus', 4, N'First encounter', N'Ability: Unaware', N'Bibarel', N'Yes'),
    (N'Sandgem Town', N'Turtwig', N'caught', N'Tortoros', 5, N'Gift', N'Ability: Shell Armor', N'Torterra', N'Yes'),
    (N'Twinleaf Town', N'Eevee', N'caught', N'Maxim', 5, N'Gift', N'Gift from Mom, Ability: Synchronize', N'Umbreon', N'Yes'),
    (N'Route 202', N'Shinx', N'caught', N'Shinra', 5, N'First encounter', N'Ability: Intimidate', N'Luxray', N'Yes'),
    (N'Trainer School', N'Mantyke', N'caught', N'Mania', 1, N'Egg', N'Ability: Swift Swim', N'Mantyke', N'Yes'),
    (N'Jubilife City', N'Bulbasaur', N'caught', N'Saurian', 5, N'Gift', N'Ability: Chlorophyll', N'Bulbasaur', N'No'),
    (N'Route 218', N'Magikarp', N'caught', N'Korius', 10, N'First encounter', N'Ability: Intimidate', N'Gyarados', N'No'),
    (N'Route 204 ~ South', N'Starly', N'caught', N'Aria', 6, N'First encounter', N'Ability: Reckless', N'Staraptor', N'Yes'),
    (N'Route 203', N'Seedot', N'caught', N'Tengu', 7, N'First encounter', N'Ability: Chlorophyll', N'Shiftry', N'No'),
    (N'Ravaged Path', N'Zubat', N'caught', N'Kuro', 6, N'First encounter', N'Ability: Inner Focus', N'Crobat', N'No'),
    (N'Oreburgh Gate', N'Geodude', N'caught', N'Gorgos', 7, N'First encounter', N'Ability: Rock Head', N'Geodude', N'No'),
    (N'Oreburgh City', N'Mudkip', N'caught', N'Swole', 10, N'Gift', N'Ability: Torrent', N'Swampert', N'Yes'),
    (N'Oreburgh City', N'Beldum', N'caught', N'Meteos', 10, N'Gift', N'Gift from Steven, Ability: Iron Fist', N'Metang', N'Yes'),
    (N'Oreburgh Mine', N'Trapinch', N'caught', N'Gladius', 9, N'First encounter', N'Ability: Levitate', N'Vibrava', N'Yes'),
    (N'Route 207', N'Machop', N'caught', N'Rudra', 9, N'First encounter', N'Ability: No Guard', N'Machamp', N'Yes'),
    (N'Route 204 ~ North', N'Ralts', N'caught', N'Xaxas', 12, N'First encounter', N'Ability: Steadfast', N'Gallade', N'Yes'),
    (N'Floaroma Town', N'Cyndaquil', N'caught', N'Phobio', 15, N'Gift', N'Ability: Blaze', N'Typhlosion', N'Yes'),
    (N'Floaroma Meadow', N'Cherubi', N'caught', N'Tulip', 12, N'First encounter', N'Ability: Flower Gift', N'Cherrim', N'Yes'),
    (N'Valley Windworks', N'Pachirisu', N'caught', N'Chrisu', 11, N'First encounter', N'Ability: Volt Absorb', N'Pachirisu', N'Yes'),
    (N'Route 205 ~ South', N'Shellos', N'caught', N'Slorgus', 13, N'First encounter', N'Ability: Sticky Hold', N'Shellos', N'No'),
    (N'Eterna Forest', N'Nincada', N'caught', N'Ninpo', 15, N'First encounter', N'Ability: Speed Boost', N'Ninjask', N'Yes'),
    (N'Eterna Forest', N'Nincada', N'caught', N'Ghaston', 15, N'Free encounter', N'Ability: Wonder Guard', N'Shedinja', N'Yes'),
    (N'Old Chateau', N'Rotom', N'caught', N'Pragma', 20, N'First encounter', N'Ability: Levitate', N'Wash-Rotom', N'Yes'),
    (N'Route 205 ~ North', N'Croagunk', N'caught', N'Venox', 16, N'First encounter', N'Ability: Dry Skin', N'Toxicroak', N'Yes'),
    (N'Eterna City', N'Poliwag', N'caught', N'Zaza', 25, N'First encounter', N'Ability: Drizzle', N'Politoed', N'Yes'),
    (N'Route 211 ~ West', N'Swablu', N'caught', N'Falania', 18, N'First encounter', N'Ability: Natural Cure', N'Altaria', N'Yes'),
    (N'Mt. Coronet', N'Feebas', N'caught', N'Vraukon', 10, N'First encounter', N'Ability: Marvel Scale', N'Milotic', N'Yes'),
    (N'Route 211 ~ East', N'Bagon', N'caught', N'Goria', 18, N'First encounter', N'Ability: Rock Head', N'Shelgon', N'Yes'),
    (N'Route 216', N'Snover', N'caught', N'Argonos', 18, N'First encounter', N'Ability: Soundproof', N'Snover', N'No'),
    (N'Mining Museum', N'Aerodactyl', N'caught', N'Atakhan', 4, N'Fossil', N'Ability: Pressure', N'Aerodactyl', N'No'),
    (N'Bike Shop', N'Togepi', N'caught', N'Marlon', 1, N'Egg', N'Egg gift from Cynthia, Ability: Serene Grace', N'Togekiss', N'Yes'),
    (N'T.G. Eterna Bldg', N'Porygon', N'caught', N'Sequenzia', 22, N'Free encounter', N'Static free encounter, Ability: Download', N'Porygon 2', N'Yes'),
    (N'Route 206', N'Mankey', N'caught', N'Hi-qui', 21, N'First encounter', N'Ability: Anger Point', N'Primeape', N'Yes'),
    (N'Wayward Cave', N'Gabite', N'caught', N'Gloria', 25, N'First encounter', N'Ability: Rough Skin', N'Gabite', N'Yes'),
    (N'Route 208', N'Goldeen', N'caught', N'Quenya', 10, N'First encounter', N'Ability: Water Veil', N'Seaking', N'Yes'),
    (N'Route 212 ~ North', N'Weepinbell', N'caught', N'Nirvas', 26, N'First encounter', N'Ability: Gluttony', N'Weepinbell', N'Yes'),
    (N'Trophy Garden', N'Pikachu', N'caught', N'Kaminari', 26, N'First encounter', N'Ability: Static', N'Pikachu', N'Yes'),
    (N'Route 209', N'Spiritomb', N'caught', N'Melinoe', 30, N'First encounter', N'Ability: Pressure', N'Spiritomb', N'Yes'),
    (N'Lost Tower', N'Duskull', N'caught', N'Fukuro', 27, N'First encounter', N'Ability: Frisk', N'Duskull', N'No'),
    (N'Solaceon Ruins', N'Unown', N'caught', N'E', 20, N'First encounter', N'Ability: Levitate', N'Unown', N'Yes'),
    (N'Route 210 ~ South', N'Kricketune', N'caught', N'Delelewoop', 28, N'First encounter', N'Ability: Swarm', N'Kricketune', N'Yes'),
    (N'Route 215', N'Linoone', N'caught', N'Liodor', 29, N'First encounter', N'Ability: Gluttony', N'Linoone', N'Yes'),
    (N'Route 214', N'Spoink', N'caught', N'Sunash', 28, N'First encounter', N'Ability: Thick Fat', N'Groink', N'Yes'),
    (N'Maniac Tunnel', N'Diglett', N'caught', N'Gaiana', 28, N'First encounter', N'Ability: Sand Veil', N'Dugtrio', N'Yes'),
    (N'Valor Lakefront', N'Nidorina', N'caught', N'Reina', 32, N'First encounter', N'Ability: Rivalry', N'Nidoqueen', N'Yes'),
    (N'Route 213', N'Remoraid', N'caught', N'Octoron', 25, N'First encounter', N'Ability: Suction Cups', N'Octillery', N'Yes'),
    (N'Pastoria City', N'Carvanha', N'caught', N'Kirisame', 25, N'First encounter', N'Ability: Rough Skin', N'Sharpedo', N'Yes'),
    (N'Great Marsh', N'Breloom', N'caught', N'Tapia', 36, N'First encounter', N'Ability: Technician', N'Breloom', N'Yes'),
    (N'Route 212 ~ South', N'Koffing', N'caught', N'Mustarda', 34, N'First encounter', N'Ability: Levitate', N'Weezing', N'Yes'),
    (N'Route 210 ~ North', N'Horsea', N'caught', N'Kaliopi', 25, N'First encounter', N'Ability: Sniper', N'Kingdra', N'Yes'),
    (N'Celestic Town', N'Relicanth', N'caught', N'Kronakai', 25, N'First encounter', N'Ability: Rock Head', N'Relicanth', N'Yes'),
    (N'Route 219', N'Wingull', N'caught', N'Pell', 38, N'First encounter', N'Ability: Drizzle', N'Pelipper', N'Yes'),
    (N'Route 220', N'Luvdisc', N'caught', N'Amora', 25, N'First encounter', N'Ability: Swift Swim', N'Luvdisc', N'Yes'),
    (N'Route 221', N'Skuntank', N'caught', N'Stinky', 40, N'First encounter', N'Ability: Aftermath', N'Skuntank', N'Yes'),
    (N'Fuego Ironworks', N'Magmar', N'caught', N'Culverin', 38, N'First encounter', N'Ability: Vital Spirit', N'Magmortar', N'Yes'),
    (N'Canalave City', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Iron Island ~ Outside', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Iron Island ~ Inside', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 217', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Acuity Lakefront', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Snowpoint Temple', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Lake Acuity', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Mt. Coronet ~ Snow Area', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Sendoff Spring', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Lake Valor', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Turnback Cave', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 222', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Sunyshore City', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 223', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Pokemon League', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Victory Road', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 224', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 225', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 226', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 227', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 228', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 229', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Route 230', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Stark Mountain ~ Outside', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL),
    (N'Stark Mountain ~ Inside', N'TBD', N'not caught', N'TBD', NULL, N'First encounter', N'Ability: TBD', N'TBD', NULL);
