-- seed.sql

INSERT INTO TrainerPokemon (Area, TrainerName, Team, Level)
VALUES
    (N'Route 201', N'PKMN Trainer Barry', N'Chimchar', N'5'),
    (N'Route 201', N'PKMN Trainer Barry', N'Piplup', N'5'),
    (N'Route 201', N'PKMN Trainer Barry', N'Turtwig', N'5'),
    (N'Route 202', N'PKMN Trainer Dawn', N'Piplup', N'9'),
    (N'Route 202', N'PKMN Trainer Dawn', N'Turtwig', N'9'),
    (N'Route 202', N'PKMN Trainer Dawn', N'Chimchar', N'9'),
    (N'Route 202', N'PKMN Trainer Lucas', N'Piplup', N'9'),
    (N'Route 202', N'PKMN Trainer Lucas', N'Turtwig', N'9'),
    (N'Route 202', N'PKMN Trainer Lucas', N'Chimchar', N'9'),
    (N'Route 202', N'Lass Natalie', N'Sentret, Bidoof', N'7, 7'),
    (N'Route 202', N'Youngster Tristan (!)', N'Hoothoot, Starly', N'7, 7'),
    (N'Route 202', N'Youngster Logan', N'Growlithe, Burmy, Zigzagoon', N'7, 7, 7'),
    (N'Route 202', N'Youngster Tristan (3)', N'Noctowl, Staravia', N'27, 27'),
    (N'Route 202', N'Youngster Tristan (5)', N'Noctowl, Staraptor', N'39, 39'),
    (N'Route 202', N'Youngster Tristan (8)', N'Noctowl, Staraptor, Pidgeot', N'59, 59, 59'),
    (N'Jubilife City Trainer School', N'Schoolkid Harrison', N'Abra, Psyduck', N'8, 8'),
    (N'Jubilife City Trainer School', N'Schoolkid Christine', N'Ralts, Staryu', N'8, 8'),
    (N'Route 204 ~ South', N'Lass Sarah', N'Shinx, Nidoran♀, Pidgey', N'8, 8, 8'),
    (N'Route 204 ~ South', N'Lass Samantha (!)', N'Oddish, Budew, Bellsprout', N'8, 8, 8'),
    (N'Route 204 ~ South', N'Youngster Tyler', N'Magikarp', N'11'),
    (N'Route 204 ~ South', N'Lass Samantha (3)', N'Luxio, Roselia, Weepinbell', N'26, 26, 26'),
    (N'Route 204 ~ South', N'Lass Samantha (5)', N'Luxio, Roselia, Weepinbell', N'38, 38, 38'),
    (N'Route 204 ~ South', N'Lass Samantha (C)', N'Luxray, Roserade, Victreebel', N'70, 70, 70'),
    (N'Route 203', N'PKMN Trainer Barry', N'Starly, Munchlax, Turtwig', N'10, 10, 11'),
    (N'Route 203', N'PKMN Trainer Barry', N'Starly, Munchlax, Chimchar', N'10, 10, 11'),
    (N'Route 203', N'PKMN Trainer Barry', N'Starly, Munchlax, Piplup', N'10, 10, 11'),
    (N'Route 203', N'Youngster Michael', N'Kricketot, Zubat, Rattata', N'9, 9, 9'),
    (N'Route 203', N'Youngster Dallas (!)', N'Shinx, Sandshrew', N'10, 10'),
    (N'Route 203', N'Youngster Sebastian', N'Nakuhita, Machop', N'10, 10'),
    (N'Route 203', N'Lass Kaitlin', N'Spearow, Cubone, Azurill', N'9, 9, 9'),
    (N'Route 203', N'Lass Madeline (!)', N'Psyduck, Sunkern', N'10, 10'),
    (N'Route 203', N'Youngster Dallas (3)', N'Luxio, Sandslash', N'27, 27'),
    (N'Route 203', N'Youngster Dallas (5)', N'Luxio, Sandslash, Bibarel', N'38, 38, 38'),
    (N'Route 203', N'Youngster Dallas (C)', N'Luxray, Sandslash, Bibarel, Golem', N'69, 69, 69, 69'),
    (N'Route 203', N'Lass Madeline (3)', N'Psyduck, Sunkern, Buneary', N'26, 26, 26'),
    (N'Route 203', N'Lass Madeline (5)', N'Golduck, Sunflora, Lopunny', N'38, 38, 38'),
    (N'Route 203', N'Lass Madeline (8)', N'Golduck, Sunflora, Lopunny', N'59, 59, 59'),
    (N'Oreburgh Gate', N'Camper Curtis', N'Seedot, Diglett', N'10, 10'),
    (N'Oreburgh Gate', N'Picnicker Diana', N'Whismur, Wooper', N'10, 10'),
    (N'Oreburgh Gate', N'Veteran Grant', N'Lucario, Golem, Staraptor', N'45, 45, 45'),
    (N'Oreburgh City', N'Reporter Helen', N'Treecko, Torchic, Mudkip', N'10, 10, 10'),
    (N'Oreburgh City', N'PKMN Trainer Steven', N'Skarmory, Aggron, Aerodactyl, Cradily, Armaldo, Metagross', N'88, 88, 88, 88, 88, 89'),
    (N'Oreburgh Mine', N'Worker Mason', N'Aron, Phanpy, Riolu', N'12, 12, 12'),
    (N'Oreburgh Mine', N'Worker Colin', N'Geodude, Whismur, Machop', N'12, 12, 12'),
    (N'Oreburgh Gym', N'Youngster Jonathon', N'Rhyhorn, Omanyte, Kabuto', N'13, 13, 13'),
    (N'Oreburgh Gym', N'Youngster Darius', N'Aron, Anorith, Lileep', N'13, 13, 13'),
    (N'Oreburgh Gym', N'Leader Roark', N'Nosepass, Bonsly, Geodude, Onix, Larvitar, Cranidos', N'15, 15, 15, 15, 15, 16'),
    (N'Jubilife City', N'Reporter Kayla', N'Bulbasaur, Charmander, Squirtle', N'5, 5, 5'),
    (N'Jubilife City', N'Galactic Grunt', N'Stunky, Silcoon', N'13, 13'),
    (N'Jubilife City', N'Galactic Grunt', N'Glameow, Cascoon', N'13, 13'),
    (N'Jubilife City', N'PKMN Trainer Dawn', N'Clefairy, Piplup', N'13, 14'),
    (N'Jubilife City', N'PKMN Trainer Dawn', N'Clefairy, Turtwig', N'13, 14'),
    (N'Jubilife City', N'PKMN Trainer Dawn', N'Clefairy, Chimchar', N'13, 14'),
    (N'Jubilife City', N'PKMN Trainer Lucas', N'Snubbull, Piplup', N'13, 14'),
    (N'Jubilife City', N'PKMN Trainer Lucas', N'Snubbull, Turtwig', N'13, 14'),
    (N'Jubilife City', N'PKMN Trainer Lucas', N'Snubbull, Chimchar', N'13, 14'),
    (N'Route 204 ~ North', N'Aroma Lady Taylor', N'Cherubi, Hoppip, Shroomish', N'13, 13, 13'),
    (N'Route 204 ~ North', N'Bug Catcher Brandon (!)', N'Wurmple, Kricketune', N'14, 14'),
    (N'Route 204 ~ North', N'Twins Liv & Liz', N'Plusle, Minun', N'15, 15'),
    (N'Route 204 ~ North', N'Bug Catcher Brandon (3)', N'Dustox, Kricketune', N'27, 27'),
    (N'Route 204 ~ North', N'Bug Catcher Brandon (5)', N'Dustox, Kricketune, Scyther', N'38, 38, 38'),
    (N'Route 204 ~ North', N'Bug Catcher Brandon (C)', N'Dustox, Kricketune, Scizor', N'70, 70, 70'),
    (N'Floaroma Town', N'Reporter Jenny', N'Chikorita, Cyndaquil, Totodile', N'15, 15, 15'),
    (N'Floaroma Meadow', N'Galactic Grunt', N'Zubat, Spinarak', N'15, 15'),
    (N'Floaroma Meadow', N'Galactic Grunt', N'Croagunk, Ledyba', N'15, 15'),
    (N'Valley Windworks', N'Galactic Grunt', N'Poochyena, Gulpin, Houndour', N'14, 14, 14'),
    (N'Valley Windworks', N'Galactic Grunt', N'Grimer, Koffing', N'15, 15'),
    (N'Valley Windworks', N'Galactic Grunt', N'Kakuna, Pineco, Metapod', N'14, 14, 14'),
    (N'Valley Windworks', N'Commander Mars', N'Zubat, Bronzor, Yanma, Purugly', N'18, 18, 18, 19'),
    (N'Route 205 ~ South', N'Hiker Daniel', N'Diglett, Shieldon, Numel', N'15, 15, 15'),
    (N'Route 205 ~ South', N'Aroma Lady Elizabeth (!)', N'Chikorita, Bulbasaur', N'16, 16'),
    (N'Route 205 ~ South', N'Camper Jacob', N'Ponyta, Mareep, Buizel', N'15, 15, 15'),
    (N'Route 205 ~ South', N'Picnicker Siena', N'Pachirisu', N'17'),
    (N'Route 205 ~ South', N'Hiker Nicholas', N'Shellos, Onix', N'16, 16'),
    (N'Route 205 ~ South', N'Battle Girl Kelsey', N'Machop, Mankey, Meditite', N'16, 16, 16'),
    (N'Route 205 ~ South', N'Picnicker Karina (!)', N'Piplup, Chimchar', N'16, 16'),
    (N'Route 205 ~ South', N'Camper Zackary (!)', N'Aipom, Slakoth, Taillow', N'15, 15, 15'),
    (N'Route 205 ~ South', N'Aroma Lady Elizabeth (3)', N'Bayleef, Ivysaur', N'27, 27'),
    (N'Route 205 ~ South', N'Aroma Lady Elizabeth (5)', N'Meganium, Venusaur', N'39, 39'),
    (N'Route 205 ~ South', N'Aroma Lady Elizabeth (C)', N'Meganium, Venusaur', N'71, 71'),
    (N'Route 205 ~ South', N'Camper Zackary (3)', N'Aipom, Vigoroth, Swellow', N'26, 26, 26'),
    (N'Route 205 ~ South', N'Camper Zackary (5)', N'Ambipom, Vigoroth, Swellow', N'38, 38, 38'),
    (N'Route 205 ~ South', N'Camper Zackary (C)', N'Ambipom, Slaking, Swellow', N'70, 70, 70'),
    (N'Route 205 ~ South', N'Picnicker Karina (3)', N'Prinplup, Monferno', N'27, 27'),
    (N'Route 205 ~ South', N'Picnicker Karina (5)', N'Empoleon, Infernape', N'39, 39'),
    (N'Route 205 ~ South', N'Picnicker Karina (C)', N'Empoleon, Infernape', N'71, 71'),
    (N'Eterna Forest', N'PKMN Trainer Cheryl', N'Drifloon, Makuhita, Wailmer, Chansey', N'19, 19, 19, 20'),
    (N'Eterna Forest', N'Bug Catcher Jack', N'Surskit, Paras, Venonat', N'16, 16, 16'),
    (N'Eterna Forest', N'Lass Briana', N'Buneary, Marill', N'17, 17'),
    (N'Eterna Forest', N'Psychic Lindsey', N'Slowpoke, Exeggcute, Natu', N'17, 17, 17'),
    (N'Eterna Forest', N'Psychic Elijah', N'Spoink, Drowzee, Baltoy', N'17, 17, 17'),
    (N'Eterna Forest', N'Bug Catcher Philip', N'Combee, Beedrill', N'17, 19'),
    (N'Eterna Forest', N'Bug Catcher Donald', N'Nincada, Dustox', N'17, 19'),
    (N'Eterna Forest', N'Psychic Kody', N'Mime Jr., Mr. Mime', N'18, 20'),
    (N'Eterna Forest', N'Psychic Rachael', N'Chingling, Chimecho', N'18, 20'),
    (N'Route 205 ~ North', N'Fisherman Joseph (!)', N'Goldeen, Poliwag, Corphish', N'18, 18, 18'),
    (N'Route 205 ~ North', N'Fisherman Andrew', N'Magikarp, Feebas, Magikarp', N'18, 18, 18'),
    (N'Route 205 ~ North', N'Fisherman Zachary', N'Krabby, Finneon', N'19, 19'),
    (N'Route 205 ~ North', N'Fisherman Joseph (5)', N'Seaking, Poliwhirl, Crawdaunt', N'38, 38, 38'),
    (N'Route 205 ~ North', N'Fisherman Joseph (C)', N'Seaking, Politoed, Crawdaunt', N'70, 70, 70'),
    (N'Route 211 ~ West', N'Ninja Boy Zach (!)', N'Zubat, Skorupi, Zubat', N'19, 19, 19'),
    (N'Route 211 ~ West', N'Hiker Louis', N'Geodude, Slugma, Beldum', N'19, 19, 19'),
    (N'Route 211 ~ West', N'Bird Keeper Alexandra', N'Natu, Swablu, Staravia', N'20, 20, 20'),
    (N'Route 211 ~ West', N'Ninja Boy Zach (5)', N'Golbat, Skorupi, Golbat', N'38, 38, 38'),
    (N'Route 211 ~ West', N'Ninja Boy Zach (8)', N'Crobat, Drapion, Crobat', N'59, 59, 59'),
    (N'Route 211 ~ West', N'Ninja Boy Zach (C)', N'Crobat, Drapion, Crobat', N'70, 70, 70'),
    (N'Route 211 ~ East', N'Bird Keeper Katherine', N'Noctowl', N'22'),
    (N'Route 211 ~ East', N'Ninja Boy Nick', N'Ninjask', N'20'),
    (N'Route 211 ~ East', N'Black Belt Sean', N'Heracross', N'22'),
    (N'Route 211 ~ East', N'Ruin Maniac Harry (!)', N'Aerodactyl', N'21'),
    (N'Route 211 ~ East', N'Ruin Maniac Harry (8)', N'Aerodactyl', N'61'),
    (N'Route 211 ~ East', N'Ruin Maniac Harry (C)', N'Aerodactyl', N'72'),
    (N'Route 216', N'Ace Trainer Blake', N'Porygon, Vigoroth', N'23, 23'),
    (N'Route 216', N'Ace Trainer Maria', N'Quagsire, Quilava, Sudowoodo', N'22, 22, 22'),
    (N'Route 216', N'Ace Trainer Laura', N'Togetic, Swellow', N'23, 23'),
    (N'Route 216', N'Skier Edward (!)', N'Snover, Snorunt, Swinub', N'20, 20, 20'),
    (N'Route 216', N'Ace Trainer Garrett', N'Mr. Mime, Nuzleaf, Scyther', N'22, 22, 22'),
    (N'Route 216', N'Black Belt Philip (!)', N'Hariyama, Machamp', N'56, 56'),
    (N'Route 216', N'Skier Bradley', N'Piloswine, Glalie', N'54, 54'),
    (N'Route 216', N'Skier Kaitlyn', N'Lapras', N'55'),
    (N'Route 216', N'Skier Andrea (!)', N'Abomasnow', N'55'),
    (N'Route 216', N'Skier Edward (8)', N'Abomasnow, Glalie, Piloswine', N'59, 59, 59'),
    (N'Route 216', N'Skier Edward (C)', N'Abomasnow, Glalie, Mamoswine', N'70, 70, 70'),
    (N'Route 216', N'Black Belt Philip (C)', N'Hariyama, Machamp, Poliwrath', N'70, 70, 70'),
    (N'Route 216', N'Skier Andrea (8)', N'Abomasnow', N'61'),
    (N'Route 216', N'Skier Andrea (C)', N'Abomasnow', N'72'),
    (N'Route 206', N'Cyclist Axel', N'Pichu, Pichu, Pikachu', N'19, 19, 19'),
    (N'Route 206', N'Cyclist Megan', N'Pidgeotto', N'21'),
    (N'Route 206', N'Cyclist James', N'Ponyta, Flaaffy', N'20, 20'),
    (N'Route 206', N'Cyclist Nicole', N'Taillow, Doduo, Wingull', N'19, 19, 19'),
    (N'Route 206', N'Cyclist John (!)', N'Farfetch''d', N'21'),
    (N'Route 206', N'Cyclist Kayla (!)', N'Voltorb, Magnemite, Electrike', N'19, 19, 19'),
    (N'Route 206', N'Cyclist Ryan', N'Luxio', N'21'),
    (N'Route 206', N'Cyclist Rachel', N'Jolteon', N'21'),
    (N'Route 206', N'Hiker Theodore', N'Torkoal', N'26'),
    (N'Route 206', N'Cyclist John (5)', N'Farfetch''d', N'40'),
    (N'Route 206', N'Cyclist John (8)', N'Farfetch''d', N'61'),
    (N'Route 206', N'Cyclist John (C)', N'Farfetch''d', N'72'),
    (N'Route 206', N'Cyclist Kayla (5)', N'Electrode, Magneton, Manectric', N'38, 38, 38'),
    (N'Route 206', N'Cyclist Kayla (8)', N'Electrode, Magneton, Manectric', N'59, 59, 59'),
    (N'Route 206', N'Cyclist Kayla (C)', N'Electrode, Magnezone, Manectric', N'70, 70, 70'),
    (N'Eterna Gym', N'Lass Caroline', N'Lotad, Cacnea, Exeggcute, Shroomish', N'22, 22, 22, 22'),
    (N'Eterna Gym', N'Aroma Lady Jenna', N'Weepinbell, Ivysaur, Gloom', N'23, 23, 23'),
    (N'Eterna Gym', N'Aroma Lady Angela', N'Roselia, Bayleef, Skiploom', N'23, 23, 23'),
    (N'Eterna Gym', N'Leader Gardenia', N'Bellossom, Tangela, Cherrim, Grotle, Breloom, Roserade', N'25, 25, 25, 25, 25, 26'),
    (N'Team Galactic Eterna Building', N'Galactic Grunt', N'Ledian, Ariados', N'24, 24'),
    (N'Team Galactic Eterna Building', N'Galactic Grunt', N'Ekans, Glameow, Nidoran♀', N'23, 23, 23'),
    (N'Team Galactic Eterna Building', N'Galactic Grunt', N'Koffing, Stunky, Nidoran♂', N'23, 23, 23'),
    (N'Team Galactic Eterna Building', N'Galactic Grunt', N'Croagunk, Golbat', N'24, 24'),
    (N'Team Galactic Eterna Building', N'Galactic Grunt', N'Cleffa', N'23'),
    (N'Team Galactic Eterna Building', N'Galactic Grunt', N'Houndour, Skorupi, Beautifly', N'23, 23, 23'),
    (N'Team Galactic Eterna Building', N'Scientist Travon', N'Drowzee, Metang, Kadabra', N'24, 24, 24'),
    (N'Team Galactic Eterna Building', N'Commander Jupiter', N'Golbat, Sableye, Tangela, Skuntank', N'26, 26, 26, 27'),
    (N'Route 207', N'Camper Anthony', N'Magby, Trapinch, Charmander', N'24, 24, 24'),
    (N'Route 207', N'Picnicker Lauren', N'Smoochum, Snubbull, Treecko', N'24, 24, 24'),
    (N'Route 207', N'Youngster Austin', N'Lombre, Gligar', N'25, 25'),
    (N'Route 207', N'Hiker Justin', N'Graveler, Sandslash', N'25, 25'),
    (N'Route 207', N'Hiker Kevin', N'Dunsparce, Dunsparce', N'25, 25'),
    (N'Route 207', N'Battle Girl Helen (!)', N'Tyrogue, Meditite, Hariyama', N'26, 26, 26'),
    (N'Route 207', N'PKMN Trainer Dawn', N'Piloswine, Clefable, Lopunny, Grotle', N'29, 29, 29, 30'),
    (N'Route 207', N'PKMN Trainer Dawn', N'Piloswine, Clefable, Lopunny, Monferno', N'29, 29, 29, 30'),
    (N'Route 207', N'PKMN Trainer Dawn', N'Piloswine, Clefable, Lopunny, Prinplup', N'29, 29, 29, 30'),
    (N'Route 207', N'PKMN Trainer Lucas', N'Piloswine, Granbull, Lickilicky, Grotle', N'29, 29, 29, 30'),
    (N'Route 207', N'PKMN Trainer Lucas', N'Piloswine, Granbull, Lickilicky, Monferno', N'29, 29, 29, 30'),
    (N'Route 207', N'PKMN Trainer Lucas', N'Piloswine, Granbull, Lickilicky, Prinplup', N'29, 29, 29, 30'),
    (N'Route 207', N'Battle Girl Helen (3)', N'Tyrogue, Meditite, Hariyama', N'28, 28, 28'),
    (N'Route 207', N'Battle Girl Helen (7)', N'Hitmontop, Medicham, Hariyama', N'54, 54, 54'),
    (N'Route 207', N'Battle Girl Helen (C)', N'Hitmontop, Medicham, Hariyama', N'72, 72, 72'),
    (N'Wayward Cave', N'PKMN Trainer Mira', N'Togetic, Haunter, Porygon2, Kadabra', N'27, 27, 27, 28'),
    (N'Wayward Cave', N'Hiker Reginald', N'Dugtrio', N'26'),
    (N'Wayward Cave', N'Hiker Lorenzo', N'Rhyhorn, Sudowoodo', N'25, 25'),
    (N'Wayward Cave', N'Lass Cassidy', N'Skitty, Meowth, Eevee', N'24, 24, 24'),
    (N'Wayward Cave', N'Youngster Wayne', N'Loudred, Raticate', N'25, 25'),
    (N'Wayward Cave', N'Picnicker Tori', N'Psyduck, Nidorina', N'25, 25'),
    (N'Wayward Cave', N'Camper Diego', N'Aipom, Nidorino', N'25, 25'),
    (N'Wayward Cave', N'Picnicker Ana', N'Illumise, Furret', N'25, 25'),
    (N'Wayward Cave', N'Camper Parker', N'Volbeat, Linoone', N'25, 25'),
    (N'Wayward Cave', N'Collector Terry', N'Gible, Bagon, Gabite', N'24, 24, 24'),
    (N'Wayward Cave', N'Ruin Maniac Gerald', N'Cubone, Probopass', N'25, 25'),
    (N'Route 208', N'Hiker Robert', N'Marowak', N'28'),
    (N'Route 208', N'Hiker Jonathan', N'Hippopotas, Shuckle, Bronzor', N'26, 26, 26'),
    (N'Route 208', N'Black Belt Kyle', N'Machoke', N'29'),
    (N'Route 208', N'Aroma Lady Hannah', N'Roselia, Sunflora', N'27, 27'),
    (N'Route 208', N'Artist William (!)', N'Smeargle, Smeargle, Smeargle', N'26, 26, 26'),
    (N'Route 208', N'Fisherman Cody', N'Whiscash, Gyarados', N'44, 44'),
    (N'Route 208', N'Hiker Alexander', N'Graveler', N'28'),
    (N'Route 208', N'Elite Four Aaron', N'Dustox, Beautifly, Venomoth, Scizor, Drapion', N'31, 31, 31, 31, 32'),
    (N'Route 208', N'Artist William (5)', N'Smeargle, Smeargle, Smeargle', N'38, 38, 38'),
    (N'Route 208', N'Artist William (8)', N'Smeargle, Smeargle, Smeargle', N'53, 53, 53'),
    (N'Route 208', N'Artist William (C)', N'Smeargle, Smeargle, Smeargle', N'70, 70, 70'),
    (N'Hearthome Gym', N'Youngster Donny', N'Gastly, Gastly, Gastly', N'27, 27, 27'),
    (N'Hearthome Gym', N'Lass Molly', N'Misdreavus', N'29'),
    (N'Hearthome Gym', N'School Kid Chance', N'Duskull, Shuppet, Duskull', N'26, 26, 26'),
    (N'Hearthome Gym', N'School Kid Mackenzie', N'Shuppet, Duskull, Shuppet', N'26, 26, 26'),
    (N'Hearthome Gym', N'Ace Trainer Allen', N'Haunter, Shedinja, Sableye', N'29, 29, 29'),
    (N'Hearthome Gym', N'Ace Trainer Catherine', N'Haunter, Rotom, Froslass', N'29, 29, 29'),
    (N'Hearthome Gym', N'Leader Fantina', N'Drifblim, Dusclops, Banette, Spiritomb, Gengar, Mismagius', N'32, 32, 32, 32, 32, 33'),
    (N'Hearthome Gym', N'PKMN Trainer Barry', N'Staravia, Heracross, Snorlax, Grotle', N'32, 32, 32, 33'),
    (N'Hearthome Gym', N'PKMN Trainer Barry', N'Staravia, Heracross, Snorlax, Monferno', N'32, 32, 32, 33'),
    (N'Hearthome Gym', N'PKMN Trainer Barry', N'Staravia, Heracross, Snorlax, Prinplup', N'32, 32, 32, 33'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Mightyena, Arbok', N'29, 29'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Kricketune', N'30'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Glameow, Koffing, Dustox', N'28, 28, 28'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Lunatone, Solrock', N'29, 29'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Solrock, Lunatone', N'29, 29'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Nincada', N'30'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Ninjask', N'30'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Shedinja', N'30'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Beedrill, Golbat', N'29, 29'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Croagunk, Seviper, Butterfree', N'28, 28, 28'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Murkrow', N'30'),
    (N'Route 212 ~ North', N'Galactic Grunt', N'Stunky, Venonat, Arbok', N'28, 28, 28'),
    (N'Route 212 ~ North', N'Commander Saturn', N'Bronzong, Octillery, Toxicroak', N'33, 33, 34'),
    (N'Route 212 ~ North', N'Gentleman Backlot', N'Wigglytuff, Raichu, Espeon', N'33, 33, 33'),
    (N'Route 212 ~ North', N'Rich Boy Jason', N'Prinplup, Azumarill', N'30, 30'),
    (N'Route 212 ~ North', N'Lady Melissa (!)', N'Cherrim, Jumpluff', N'30, 30'),
    (N'Route 212 ~ North', N'Gentleman Jeremy (!)', N'Chatot', N'31'),
    (N'Route 212 ~ North', N'Socialite Reina (!)', N'Delcatty', N'31'),
    (N'Route 212 ~ North', N'Policeman Bobby', N'Noctowl', N'31'),
    (N'Route 212 ~ North', N'Policeman Alex', N'Machamp', N'31'),
    (N'Route 212 ~ North', N'Policeman Dylan', N'Arcanine', N'31'),
    (N'Route 212 ~ North', N'Policeman Caleb', N'Granbull', N'31'),
    (N'Route 212 ~ North', N'Lady Melissa (5)', N'Gloom, Cherrim, Jumpluff', N'38, 38, 38'),
    (N'Route 212 ~ North', N'Lady Melissa (8)', N'Bellossom, Cherrim, Jumpluff', N'59, 59, 59'),
    (N'Route 212 ~ North', N'Lady Melissa (C)', N'Bellossom, Cherrim, Jumpluff', N'70, 70, 70'),
    (N'Route 212 ~ North', N'Gentleman Jeremy (5)', N'Chatot', N'41'),
    (N'Route 212 ~ North', N'Gentleman Jeremy (8)', N'Chatot', N'62'),
    (N'Route 212 ~ North', N'Gentleman Jeremy (C)', N'Chatot', N'73'),
    (N'Route 212 ~ North', N'Socialite Reina (8)', N'Delcatty', N'62'),
    (N'Route 212 ~ North', N'Socialite Reina (C)', N'Delcatty', N'73'),
    (N'Route 209', N'PKMN Breeder Albert (!)', N'Tyrogue, Chingling, Bonsly, Magby, Elekid, Mime Jr.', N'26, 26, 26, 26, 26, 26'),
    (N'Route 209', N'Twins Emma & Lil', N'Vaporeon, Flareon', N'30, 30'),
    (N'Route 209', N'Poké Kid Danielle (!)', N'Pichu, Pikachu, Raichu', N'28, 29, 30'),
    (N'Route 209', N'PKMN Breeder Jennifer (!)', N'Azurill, Togepi, Cleffa, Igglybuff, Smoochum, Budew', N'26, 26, 26, 26, 26, 26'),
    (N'Route 209', N'Cowgirl Shelley', N'Ponyta, Bibarel', N'30, 30'),
    (N'Route 209', N'Jogger Richard', N'Dodrio', N'31'),
    (N'Route 209', N'Jogger Raul', N'Fearow', N'31'),
    (N'Route 209', N'Young Couple Ty & Sue', N'Illumise, Volbeat', N'31, 31'),
    (N'Route 209', N'PKMN Breeder Albert (5)', N'Hitmontop, Chimecho, Sudowoodo, Magmar, Electabuzz, Mr. Mime', N'37, 37, 37, 37, 37, 37'),
    (N'Route 209', N'PKMN Breeder Albert (8)', N'Hitmontop, Chimecho, Sudowoodo, Magmar, Electabuzz, Mr. Mime', N'57, 57, 57, 57, 57, 57'),
    (N'Route 209', N'PKMN Breeder Albert (C)', N'Hitmontop, Chimecho, Sudowoodo, Magmar, Electabuzz, Mr. Mime', N'68, 68, 68, 68, 68, 68'),
    (N'Route 209', N'Poké Kid Danielle (5)', N'Pikachu, Pikachu, Raichu', N'37, 37, 38'),
    (N'Route 209', N'Poké Kid Danielle (8)', N'Pikachu, Raichu, Raichu', N'57, 58, 58'),
    (N'Route 209', N'Poké Kid Danielle (C)', N'Raichu, Raichu, Raichu', N'69, 69, 69'),
    (N'Route 209', N'PKMN Breeder Jennifer (5)', N'Marill, Togetic, Clefairy, Jigglypuff, Jynx, Roselia', N'37, 37, 37, 37, 37, 37'),
    (N'Route 209', N'PKMN Breeder Jennifer (8)', N'Azumarill, Togekiss, Clefable, Wigglytuff, Jynx, Roserade', N'57, 57, 57, 57, 57, 57'),
    (N'Route 209', N'PKMN Breeder Jennifer (C)', N'Azumarill, Togekiss, Clefable, Wigglytuff, Jynx, Roserade', N'68, 68, 68, 68, 68, 68'),
    (N'Lost Tower', N'Youngster Oliver', N'Shellos, Barboach, Mothim', N'31, 31, 31'),
    (N'Lost Tower', N'Pokéfan Leonard', N'Plusle, Minun, Pachirisu', N'31, 31, 31'),
    (N'Lost Tower', N'Roughneck Kirby', N'Cleffa', N'33'),
    (N'Lost Tower', N'Pokéfan Rebekah', N'Clefairy, Wailmer, Bonsly, Skitty', N'30, 30, 30, 30'),
    (N'Lost Tower', N'Young Couple Mike & Nat', N'Murkrow, Misdreavus', N'33, 33'),
    (N'Lost Tower', N'Belle & Pa Beth & Bob', N'Ponyta, Flaaffy', N'33, 33'),
    (N'Solaceon Ruins', N'Ruin Maniac Karl', N'Bronzor, Graveler, Sandslash', N'31, 31, 31'),
    (N'Route 210 ~ South', N'Twins Teri & Tia', N'Furret, Linoone', N'32, 32'),
    (N'Route 210 ~ South', N'Jogger Wyatt', N'Electrode', N'33'),
    (N'Route 210 ~ South', N'PKMN Breeder Kahlil', N'Riolu, Chingling, Munchlax', N'31, 31, 31'),
    (N'Route 210 ~ South', N'PKMN Breeder Amber', N'Mantyke, Happiny, Wynaut', N'31, 31, 31'),
    (N'Route 210 ~ South', N'Belle & Pa Ava & Matt', N'Tauros, Miltank', N'33, 33'),
    (N'Route 210 ~ South', N'Rancher Marco (!)', N'Rapidash', N'33'),
    (N'Route 210 ~ South', N'Collector Fernando', N'Dratini, Dragonair', N'31, 33'),
    (N'Route 210 ~ South', N'Collector Edwin', N'Bagon, Shelgon', N'31, 33'),
    (N'Route 210 ~ South', N'Waitress Kati', N'Clefable', N'33'),
    (N'Route 210 ~ South', N'Rancher Marco (8)', N'Rapidash, Tauros, Miltank', N'59, 59, 59'),
    (N'Route 210 ~ South', N'Rancher Marco (C)', N'Rapidash, Tauros, Miltank', N'70, 70, 70'),
    (N'Route 215', N'Black Belt Derek', N'Combusken, Hitmonlee', N'34, 34'),
    (N'Route 215', N'Black Belt Gregory', N'Primeape, Hitmonchan', N'34, 34'),
    (N'Route 215', N'Black Belt Nathaniel', N'Machoke, Hitmontop', N'34, 34'),
    (N'Route 215', N'Jogger Scott', N'Staraptor', N'34'),
    (N'Route 215', N'Ruin Maniac Calvin', N'Marowak, Rampardos', N'33, 33'),
    (N'Route 215', N'Jogger Craig (!)', N'Luxray', N'34'),
    (N'Route 215', N'Ace Trainer Dennis (!)', N'Gligar, Gyarados, Drifblim', N'35, 35, 35'),
    (N'Route 215', N'Ace Trainer Maya (!)', N'Lickitung, Gardevoir, Roserade', N'35, 35, 35'),
    (N'Route 215', N'Jogger Craig (8)', N'Luxray, Luxray', N'60, 60'),
    (N'Route 215', N'Jogger Craig (C)', N'Luxray, Luxray', N'72, 72'),
    (N'Route 215', N'Ace Trainer Dennis (7)', N'Gliscor, Gyarados, Drifblim', N'62, 62, 62'),
    (N'Route 215', N'Ace Trainer Dennis (S)', N'Gliscor, Gyarados, Drifblim', N'77, 77, 77'),
    (N'Route 215', N'Ace Trainer Maya (7)', N'Lickilicky, Gardevoir, Roserade', N'62, 62, 62'),
    (N'Route 215', N'Ace Trainer Maya (S)', N'Lickilicky, Gardevoir, Roserade', N'77, 77, 77'),
    (N'Veilstone Gym', N'Black Belt Colby', N'Machop, Meditite, Croagunk, Mankey, Makuhita', N'33, 33, 33, 33, 33'),
    (N'Veilstone Gym', N'Black Belt Darren', N'Primeape, Hariyama, Breloom', N'35, 35, 35'),
    (N'Veilstone Gym', N'Black Belt Jeffery', N'Heracross, Poliwrath', N'36, 36'),
    (N'Veilstone Gym', N'Black Belt Rafael', N'Hitmonchan, Hitmonlee, Hitmontop', N'35, 35, 35'),
    (N'Veilstone Gym', N'Leader Maylene', N'Medicham, Machamp, Infernape, Toxicroak, Gallade, Lucario', N'38, 38, 38, 38, 38, 39'),
    (N'Veilstone City', N'Dragon Tamer Nils', N'Dragonair, Shelgon, Vibrava, Kingdra', N'35, 35, 35, 36'),
    (N'Veilstone City', N'Team Galactic Grunt', N'Weezing, Golbat, Venomoth', N'35, 35, 35'),
    (N'Veilstone City', N'Team Galactic Grunt', N'Skuntank, Dustox, Wormadam', N'35, 35, 35'),
    (N'Route 214', N'PI Carlos (!)', N'Dugtrio', N'36'),
    (N'Route 214', N'Collector Douglas', N'Jolteon, Vaporeon, Flareon', N'33, 33, 33'),
    (N'Route 214', N'Collector Brady', N'Kangaskhan, Tropius, Swalot', N'33, 33, 33'),
    (N'Route 214', N'Ruin Maniac Bryan', N'Anorith, Lileep, Aerodactyl', N'33, 33, 33'),
    (N'Route 214', N'Ruin Maniac Ronald', N'Relicanth', N'35'),
    (N'Route 214', N'Collector Jamal', N'Lapras', N'35'),
    (N'Route 214', N'Beauty Devon', N'Wormadam, Wormadam, Wormadam', N'33, 33, 33'),
    (N'Route 214', N'Psychic Mitchell (!)', N'Kadabra, Grumpig, Hypno', N'34, 34, 34'),
    (N'Route 214', N'Psychic Abigail (!)', N'Kirlia, Chimecho, Girafarig', N'34, 34, 34'),
    (N'Route 214', N'PI Carlos (8)', N'Dugtrio', N'62'),
    (N'Route 214', N'PI Carlos (C)', N'Dugtrio, Lapras, Kingler', N'70, 70, 70'),
    (N'Route 214', N'Psychic Mitchell (8)', N'Alakazam, Grumpig, Hypno', N'60, 60, 60'),
    (N'Route 214', N'Psychic Mitchell (C)', N'Alakazam, Grumpig, Hypno', N'72, 72, 72'),
    (N'Route 214', N'Psychic Abigail (8)', N'Gardevoir, Chimecho, Girafarig', N'60, 60, 60'),
    (N'Route 214', N'Psychic Abigail (C)', N'Gardevoir, Chimecho, Girafarig', N'72, 72, 72'),
    (N'Seven Stars Restaurant', N'Artist Ismael', N'Smeargle', N'37'),
    (N'Seven Stars Restaurant', N'Beauty Harley', N'Golduck', N'37'),
    (N'Seven Stars Restaurant', N'Rich Boy Roman', N'Arcanine', N'37'),
    (N'Seven Stars Restaurant', N'Lady Kylie', N'Vileplume', N'37'),
    (N'Seven Stars Restaurant', N'Gentleman Leonardo', N'Chatot', N'37'),
    (N'Seven Stars Restaurant', N'Socialite Rebecca', N'Persian', N'37'),
    (N'Seven Stars Restaurant', N'Collector Eugene', N'Milotic', N'37'),
    (N'Seven Stars Restaurant', N'Aroma Lady Alison', N'Meganium', N'37'),
    (N'Seven Stars Restaurant', N'School Kid Esteban', N'Quagsire', N'37'),
    (N'Seven Stars Restaurant', N'Pokéfan Meredith', N'Pachirisu', N'37'),
    (N'Seven Stars Restaurant', N'Veteran Emanuel', N'Blaziken', N'37'),
    (N'Seven Stars Restaurant', N'Lass Blythe', N'Lopunny', N'37'),
    (N'Seven Stars Restaurant', N'Cameraman Darryl', N'Magneton', N'37'),
    (N'Seven Stars Restaurant', N'Reporter Valerie', N'Loudred', N'37'),
    (N'Seven Stars Restaurant', N'PI Kendrick', N'Rhydon', N'37'),
    (N'Seven Stars Restaurant', N'Beauty Gabriella', N'Lumineon', N'37'),
    (N'Seven Stars Restaurant', N'Scientist Emilio', N'Alakazam', N'37'),
    (N'Seven Stars Restaurant', N'Pokémon Breeder Kaylee', N'Azumarill', N'37'),
    (N'Route 213', N'Beauty Cyndy (!)', N'Delcatty, Persian', N'37, 37'),
    (N'Route 213', N'Fisherman Kenneth', N'Carvanha, Remoraid, Horsea', N'36, 36, 36'),
    (N'Route 213', N'Tuber Jared (!)', N'Gastrodon', N'37'),
    (N'Route 213', N'Tuber Chelsea (!)', N'Azumarill', N'37'),
    (N'Route 213', N'Swimmer Haley', N'Golduck, Mantine, Corsola', N'43, 43, 43'),
    (N'Route 213', N'Swimmer Sheltin', N'Gyarados, Gyarados, Gyarados', N'43, 43, 43'),
    (N'Route 213', N'Sailor Paul', N'Politoed', N'45'),
    (N'Route 213', N'Swimmer Evan', N'Quagsire, Sharpedo', N'44, 44'),
    (N'Route 213', N'Swimmer Mary', N'Pelipper, Lumineon', N'44, 44'),
    (N'Route 213', N'Galactic Grunt', N'Toxicroak', N'41'),
    (N'Route 213', N'Beauty Cyndy (8)', N'Delcatty, Persian, Purugly', N'59, 59, 59'),
    (N'Route 213', N'Beauty Cyndy (C)', N'Delcatty, Persian, Purugly', N'70, 70, 70'),
    (N'Route 213', N'Tuber Jared (5)', N'Gastrodon', N'39'),
    (N'Route 213', N'Tuber Jared (C)', N'Gastrodon', N'69'),
    (N'Route 213', N'Tuber Chelsea (8)', N'Azumarill', N'59'),
    (N'Route 213', N'Tuber Chelsea (C)', N'Azumarill', N'69'),
    (N'Route 212 ~ South', N'Parasol Lady Sabrina', N'Castform', N'39'),
    (N'Route 212 ~ South', N'Scientist Shaun (!)', N'Magneton, Electrode, Porygon2', N'37, 37, 37'),
    (N'Route 212 ~ South', N'Pokémon Ranger Taylor (!)', N'Carnivine, Kecleon, Electabuzz', N'39, 39, 39'),
    (N'Route 212 ~ South', N'Parasol Lady Alexa (!)', N'Seadra, Golduck', N'38, 38'),
    (N'Route 212 ~ South', N'Fisherman Juan', N'Shellder, Clamperl, Cloyster', N'36, 36, 39'),
    (N'Route 212 ~ South', N'Fisherman Josh', N'Remoraid, Goldeen, Octillery', N'36, 36, 39'),
    (N'Route 212 ~ South', N'Fisherman Travis', N'Barboach, Qwilfish', N'38, 38'),
    (N'Route 212 ~ South', N'Collector Dean', N'Espeon, Umbreon, Glaceon', N'37, 37, 37'),
    (N'Route 212 ~ South', N'Policeman Danny', N'Growlithe, Machoke, Noctowl', N'37, 37, 37'),
    (N'Route 212 ~ South', N'Scientist Stefano', N'Weezing, Muk', N'38, 38'),
    (N'Route 212 ~ South', N'Pokémon Ranger Allison (!)', N'Milotic, Leafeon, Jynx', N'39, 39, 39'),
    (N'Route 212 ~ South', N'Pokémon Ranger Jeffrey', N'Magmar, Manectric, Nidoking', N'39, 39, 39'),
    (N'Route 212 ~ South', N'Scientist Shaun (5)', N'Magneton, Electrode, Porygon2', N'38, 38, 38'),
    (N'Route 212 ~ South', N'Scientist Shaun (8)', N'Magneton, Electrode, Porygon2', N'59, 59, 59'),
    (N'Route 212 ~ South', N'Scientist Shaun (C)', N'Magnezone, Electrode, Porygon-Z', N'70, 70, 70'),
    (N'Route 212 ~ South', N'Pokémon Ranger Taylor (5)', N'Carnivine, Kecleon, Electabuzz', N'40, 40, 40'),
    (N'Route 212 ~ South', N'Pokémon Ranger Taylor (8)', N'Carnivine, Kecleon, Electivire', N'60, 60, 60'),
    (N'Route 212 ~ South', N'Pokémon Ranger Taylor (C)', N'Carnivine, Kecleon, Electivire', N'71, 71, 71'),
    (N'Route 212 ~ South', N'Pokémon Ranger Allison (5)', N'Milotic, Leafeon, Jynx', N'40, 40, 40'),
    (N'Route 212 ~ South', N'Pokémon Ranger Allison (8)', N'Milotic, Leafeon, Jynx', N'60, 60, 60'),
    (N'Route 212 ~ South', N'Pokémon Ranger Allison (C)', N'Milotic, Leafeon, Jynx', N'71, 71, 71'),
    (N'Route 212 ~ South', N'Parasol Lady Alexa (5)', N'Seadra, Golduck', N'39, 39'),
    (N'Route 212 ~ South', N'Parasol Lady Alexa (8)', N'Kingdra, Golduck', N'60, 60'),
    (N'Route 212 ~ South', N'Parasol Lady Alexa (C)', N'Kingdra, Golduck', N'71, 71'),
    (N'Pastoria City', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Arcanine, Torterra', N'41, 41, 41, 41, 41, 42'),
    (N'Pastoria City', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Breloom, Infernape', N'41, 41, 41, 41, 41, 42'),
    (N'Pastoria City', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Breloom, Arcanine, Empoleon', N'41, 41, 41, 41, 41, 42'),
    (N'Pastoria Gym', N'Tuber Jacky', N'Bibarel, Wartortle, Sealeo', N'39, 39, 39'),
    (N'Pastoria Gym', N'Fisherman Walter', N'Whiscash, Lanturn, Seaking', N'39, 39, 39'),
    (N'Pastoria Gym', N'Sailor Damian', N'Pelipper, Croconaw, Golduck', N'39, 39, 39'),
    (N'Pastoria Gym', N'Tuber Caitlyn', N'Azumarill, Marshtomp, Dewgong', N'39, 39, 39'),
    (N'Pastoria Gym', N'Fisherman Erick', N'Lumineon, Tentacruel, Kingler', N'39, 39, 39'),
    (N'Pastoria Gym', N'Sailor Samson', N'Slowbro, Gastrodon, Mantine', N'39, 39, 39'),
    (N'Pastoria Gym', N'Leader Wake', N'Quagsire, Gyarados, Poliwrath, Ludicolo, Sharpedo, Floatzel', N'43, 43, 43, 43, 43, 44'),
    (N'Route 210 ~ North', N'Ninja Boy Fabian', N'Toxicroak', N'41'),
    (N'Route 210 ~ North', N'Ninja Boy Brennan', N'Ninjask', N'41'),
    (N'Route 210 ~ North', N'Ninja Boy Bruce', N'Skuntank', N'41'),
    (N'Route 210 ~ North', N'Ninja Boy Joel', N'Scyther, Spinda, Golbat', N'39, 39, 39'),
    (N'Route 210 ~ North', N'Ace Trainer Alyssa', N'Ambipom, Starmie, Torterra', N'42, 42, 42'),
    (N'Route 210 ~ North', N'Double Team Zac & Jen', N'Gyarados, Gliscor, Victreebel, Typhlosion, Ursaring, Ampharos', N'42, 42, 42, 42, 42, 42'),
    (N'Route 210 ~ North', N'Ace Trainer Ernest', N'Politoed, Pinsir, Probopass, Xatu', N'41, 41, 41, 41'),
    (N'Route 210 ~ North', N'Ninja Boy Davido', N'Ninetales', N'41'),
    (N'Route 210 ~ North', N'Black Belt Adam', N'Machamp, Blaziken, Heracross', N'42, 42, 42'),
    (N'Route 210 ~ North', N'Ninja Boy Nathan', N'Swalot, Dustox, Mothim', N'39, 39, 39'),
    (N'Route 210 ~ North', N'Bird Keeper Brianna (!)', N'Dodrio, Pidgeot, Skarmory', N'42, 42, 42'),
    (N'Route 210 ~ North', N'Veteran Brian (!)', N'Tangrowth, Rapidash, Feraligatr', N'43, 43, 43'),
    (N'Route 210 ~ North', N'Dragon Tamer Patrick (!)', N'Gabite, Shelgon, Vibrava, Dragonair', N'41, 41, 41, 41'),
    (N'Route 210 ~ North', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Vaporeon, Torterra', N'44, 44, 44, 44, 44, 45'),
    (N'Route 210 ~ North', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Jolteon, Infernape', N'44, 44, 44, 44, 44, 45'),
    (N'Route 210 ~ North', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Flareon, Empoleon', N'44, 44, 44, 44, 44, 45'),
    (N'Route 210 ~ North', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Vaporeon, Torterra', N'44, 44, 44, 44, 44, 45'),
    (N'Route 210 ~ North', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Jolteon, Infernape', N'44, 44, 44, 44, 44, 45'),
    (N'Route 210 ~ North', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Flareon, Empoleon', N'44, 44, 44, 44, 44, 45'),
    (N'Route 210 ~ North', N'Bird Keeper Brianna (8)', N'Dodrio, Pidgeot, Skarmory', N'60, 60, 60'),
    (N'Route 210 ~ North', N'Bird Keeper Brianna (C)', N'Dodrio, Pidgeot, Skarmory', N'71, 71, 71'),
    (N'Route 210 ~ North', N'Veteran Brian (8)', N'Tangrowth, Rapidash, Feraligatr', N'61, 61, 61'),
    (N'Route 210 ~ North', N'Veteran Brian (C)', N'Tangrowth, Rapidash, Feraligatr', N'75, 75, 75'),
    (N'Route 210 ~ North', N'Dragon Tamer Patrick (8)', N'Gabite, Shelgon, Vibrava, Dragonair', N'58, 58, 58, 58'),
    (N'Route 210 ~ North', N'Dragon Tamer Patrick (C)', N'Garchomp, Salamence, Flygon, Dragonite', N'70, 70, 70, 70'),
    (N'Celestic Town', N'Galactic Grunt', N'Houndoom, Golbat, Beedrill', N'43, 43, 43'),
    (N'Celestic Town', N'Galactic Boss Cyrus', N'Crobat, Honchkrow, Magnezone, Weavile', N'45, 45, 45, 46'),
    (N'Route 218', N'Fisherman Miguel (!)', N'Huntail, Gorebyss', N'44, 44'),
    (N'Route 218', N'Fisherman Luc', N'Crawdaunt', N'45'),
    (N'Route 218', N'Sailor Skyler', N'Omastar, Kabutops, Relicanth', N'43, 43, 43'),
    (N'Route 218', N'Guitarist Tony (!)', N'Kricketune, Exploud', N'44, 44'),
    (N'Route 218', N'Fisherman Miguel (C)', N'Clamperl, Huntail, Gorebyss', N'70, 70, 70'),
    (N'Route 218', N'Guitarist Tony (C)', N'Kricketune, Exploud', N'71, 71'),
    (N'Fuego Ironworks', N'Worker Dillan', N'Machop, Machoke, Machamp', N'42, 43, 44'),
    (N'Fuego Ironworks', N'Worker Holden', N'Magnemite, Magnemite, Steelix', N'42, 42, 45'),
    (N'Fuego Ironworks', N'Worker Conrad', N'Magmar, Magcargo, Rapidash', N'43, 43, 43'),
    (N'Route 219', N'Tuber Mariel', N'Azumarill, Vaporeon', N'43, 43'),
    (N'Route 219', N'Tuber Trenton', N'Poliwhirl, Gastrodon, Bibarel', N'42, 42, 42'),
    (N'Route 220', N'Swimmer Jessica', N'Seadra, Luvdisc, Seaking', N'43, 43, 43'),
    (N'Route 220', N'Swimmer Erica', N'Lumineon, Corsola', N'44, 44'),
    (N'Route 220', N'Swimmer Adrian', N'Octillery, Tentacruel, Slowking', N'43, 43, 43'),
    (N'Route 220', N'Swimmer Vincent', N'Wailord', N'45'),
    (N'Route 220', N'Swimmer Claire', N'Starmie, Blastoise', N'44, 44'),
    (N'Route 220', N'Swimmer Erik', N'Politoed, Lanturn', N'44, 44'),
    (N'Route 220', N'Swimmer Katelyn', N'Floatzel, Medicham, Seaking', N'43, 43, 43'),
    (N'Route 221', N'Swimmer Dillon', N'Swampert', N'46'),
    (N'Route 221', N'Swimmer Vanessa', N'Milotic', N'46'),
    (N'Route 221', N'Fisherman Cory', N'Whiscash, Kingler, Gyarados', N'44, 44, 44'),
    (N'Route 221', N'Ace Trainer Shannon (!)', N'Vileplume, Gardevoir, Lopunny, Nidoqueen', N'45, 45, 45, 45'),
    (N'Route 221', N'Ace Trainer Jake (!)', N'Claydol, Charizard, Exeggutor, Absol', N'45, 45, 45, 45'),
    (N'Route 221', N'Collector Ivan (!)', N'Togekiss, Blissey', N'45, 45'),
    (N'Route 221', N'Ace Trainer Shannon (C)', N'Vileplume, Gardevoir, Lopunny, Nidoqueen', N'72, 72, 72, 72'),
    (N'Route 221', N'Ace Trainer Jake (C)', N'Claydol, Charizard, Exeggutor, Absol', N'72, 72, 72, 72'),
    (N'Route 221', N'Collector Ivan (C)', N'Togekiss, Blissey', N'72, 72'),
    (N'Pal Park', N'Castle Valet Darach', N'Gallade, Empoleon, Alakazam, Metagross, Staraptor, Entei', N'48, 48, 48, 48, 48, 48'),
    (N'Canalave City', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Arcanine, Torterra', N'48, 48, 48, 48, 48, 49'),
    (N'Canalave City', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Breloom, Infernape', N'48, 48, 48, 48, 48, 49'),
    (N'Canalave City', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Breloom, Arcanine, Empoleon', N'48, 48, 48, 48, 48, 49'),
    (N'Iron Island', N'PKMN Trainer Riley', N'Absol, Ursaring, Metagross, Salamence, Slaking, Lucario', N'49, 49, 49, 49, 49, 50'),
    (N'Iron Island', N'Camper Lawrence', N'Charmeleon, Ambipom, Floatzel', N'46, 46, 46'),
    (N'Iron Island', N'Picnicker Summer', N'Grovyle, Fearow, Raichu', N'46, 46, 46'),
    (N'Iron Island', N'Worker Noel', N'Donphan', N'48'),
    (N'Iron Island', N'Worker Braden', N'Camerupt', N'48'),
    (N'Iron Island', N'Hiker Damon', N'Pupitar, Probopass, Steelix', N'46, 46, 46'),
    (N'Iron Island', N'Hiker Maurice', N'Rhydon, Golem', N'47, 47'),
    (N'Iron Island', N'Black Belt Kendal', N'Poliwrath, Hariyama', N'48, 48'),
    (N'Iron Island', N'Battle Girl Tyler', N'Hitmontop, Primeape', N'48, 48'),
    (N'Iron Island', N'Worker Brendon', N'Magneton, Machoke', N'47, 47'),
    (N'Iron Island', N'Worker Quentin', N'Lairon, Graveler', N'47, 47'),
    (N'Iron Island', N'Ace Trainer Jonah', N'Masquerain, Cradily, Hippowdon', N'48, 48, 48'),
    (N'Iron Island', N'Ace Trainer Brenda', N'Gardevoir, Lopunny, Medicham', N'48, 48, 48'),
    (N'Iron Island', N'Galactic Grunt', N'Golbat, Houndoom, Muk', N'46, 46, 46'),
    (N'Iron Island', N'Galactic Grunt', N'Purugly, Toxicroak, Skuntank', N'46, 46, 46'),
    (N'Canalave Gym', N'Black Belt Ricky', N'Steelix', N'51'),
    (N'Canalave Gym', N'Worker Gary', N'Magnemite, Aron, Bronzor, Beldum, Shieldon', N'46, 46, 46, 46, 46'),
    (N'Canalave Gym', N'Worker Jackson', N'Magneton, Lairon, Metang', N'48, 48, 48'),
    (N'Canalave Gym', N'Ace Trainer Cesar', N'Empoleon, Scizor, Metagross', N'50, 50, 50'),
    (N'Canalave Gym', N'Worker Gerardo', N'Probopass, Forretress', N'49, 49'),
    (N'Canalave Gym', N'Black Belt David', N'Lucario', N'51'),
    (N'Canalave Gym', N'Ace Trainer Breanna', N'Skarmory, Mawile, Wormadam', N'50, 50, 50'),
    (N'Canalave Gym', N'Leader Bryon', N'Bronzong, Magnezone, Steelix, Forretress, Aggron, Bastiodon', N'52, 52, 52, 52, 52, 53'),
    (N'Lake Valor', N'Galactic Grunt', N'Purugly', N'50'),
    (N'Lake Valor', N'Galactic Grunt', N'Houndoom', N'50'),
    (N'Lake Valor', N'Galactic Grunt', N'Skuntank', N'50'),
    (N'Lake Valor', N'Commander Saturn', N'Alakazam, Octillery, Bronzong, Rhydon, Toxicroak', N'52, 52, 52, 52, 53'),
    (N'Lake Verity', N'Galactic Grunt', N'Beautifly, Butterfree', N'50, 50'),
    (N'Lake Verity', N'Galactic Grunt', N'Dustox, Beedrill', N'50, 50'),
    (N'Lake Verity', N'Galactic Grunt', N'Nidorino, Golbat, Wormadam', N'49, 49, 49'),
    (N'Lake Verity', N'Galactic Grunt', N'Nidorina, Golbat, Mothim', N'49, 49, 49'),
    (N'Lake Verity', N'Commander Mars', N'Crobat, Yanmega, Bronzong, Kangaskhan, Purugly', N'52, 52, 52, 52, 53'),
    (N'Route 217', N'Ace Trainer Dalton (!)', N'Magmortar, Venusaur, Kingdra', N'52, 52, 52'),
    (N'Route 217', N'Skier Shawn', N'Snover, Snover, Abomasnow', N'49, 49, 52'),
    (N'Route 217', N'Ninja Boy Matthew', N'Crobat', N'51'),
    (N'Route 217', N'Skier Madison (!)', N'Smoochum, Snorunt, Jynx', N'49, 49, 52'),
    (N'Route 217', N'Ninja Boy Ethan', N'Drapion', N'51'),
    (N'Route 217', N'Skier Bjorn (!)', N'Swinub, Swinub, Piloswine', N'49, 49, 52'),
    (N'Route 217', N'Skier Lexie', N'Dewgong, Glaceon', N'51, 51'),
    (N'Route 217', N'Black Belt Luke', N'Machamp, Toxicroak, Lucario', N'51, 51, 51'),
    (N'Route 217', N'Ace Trainer Olivia (!)', N'Shiftry, Altaria, Blissey', N'52, 52, 52'),
    (N'Route 217', N'Ace Trainer Dalton (C)', N'Magmortar, Venusaur, Kingdra', N'72, 72, 72'),
    (N'Route 217', N'Skier Madison (8)', N'Jynx, Froslass, Jynx', N'59, 59, 59'),
    (N'Route 217', N'Skier Madison (C)', N'Jynx, Froslass, Jynx', N'70, 70, 70'),
    (N'Route 217', N'Skier Bjorn (8)', N'Piloswine, Piloswine, Mamoswine', N'59, 59, 59'),
    (N'Route 217', N'Skier Bjorn (C)', N'Mamoswine, Mamoswine, Mamoswine', N'72, 72, 72'),
    (N'Route 217', N'Ace Trainer Olivia (C)', N'Shiftry, Altaria, Blissey', N'72, 72, 72'),
    (N'Snowpoint City', N'Ace Trainer Aran', N'Heracross, Typhlosion, Tyranitar', N'54, 54, 54'),
    (N'Snowpoint City', N'Ace Trainer Nephenee', N'Blissey, Meganium, Feraligatr', N'54, 54, 54'),
    (N'Snowpoint Gym', N'Ace Trainer Anton', N'Snorunt, Glalie, Glalie', N'51, 54, 54'),
    (N'Snowpoint Gym', N'Ace Trainer Savannah', N'Seel, Jynx, Dewgong', N'51, 54, 54'),
    (N'Snowpoint Gym', N'Ace Trainer Alicia', N'Spheal, Sealeo, Walrein', N'51, 53, 55'),
    (N'Snowpoint Gym', N'Ace Trainer Isaiah', N'Abomasnow, Delibird', N'54, 54'),
    (N'Snowpoint Gym', N'Ace Trainer Brenna', N'Dewgong, Cloyster, Lapras', N'53, 53, 53'),
    (N'Snowpoint Gym', N'Ace Trainer Sergio', N'Swinub, Piloswine, Mamoswine', N'51, 53, 55'),
    (N'Snowpoint Gym', N'Leader Candice', N'Abomasnow, Weavile, Glaceon, Walrein, Mamoswine, Froslass', N'55, 55, 55, 55, 55, 56'),
    (N'Galactic HQ', N'Galactic Grunt', N'Golbat, Dustox, Parasect', N'53, 53, 53'),
    (N'Galactic HQ', N'Galactic Grunt', N'Murkrow, Houndoom', N'54, 54'),
    (N'Galactic HQ', N'Galactic Grunt', N'Beautifly, Purugly, Vespiquen', N'53, 53, 53'),
    (N'Galactic HQ', N'Galactic Grunt', N'Toxicroak, Skuntank', N'54, 54'),
    (N'Galactic HQ', N'Scientist Fredrick', N'Kirlia, Kadabra, Magneton', N'53, 53, 53'),
    (N'Galactic HQ', N'Galactic Grunt', N'Scyther, Skuntank', N'54, 54'),
    (N'Galactic HQ', N'Galactic Grunt', N'Pinsir, Toxicroak', N'54, 54'),
    (N'Galactic HQ', N'Galactic Grunt', N'Golbat, Mightyena, Ariados', N'53, 53, 53'),
    (N'Galactic HQ', N'Galactic Grunt', N'Golbat, Venomoth, Cacturne', N'53, 53, 53'),
    (N'Galactic HQ', N'Scientist Darrius', N'Porygon-Z', N'55'),
    (N'Galactic HQ', N'Galactic Grunt', N'Muk, Arbok', N'54, 54'),
    (N'Galactic HQ', N'Galactic Grunt', N'Forretress, Seviper, Yanmega', N'53, 53, 53'),
    (N'Galactic HQ', N'Galactic Boss Cyrus', N'Crobat, Honchkrow, Houndoom, Magnezone, Weavile', N'57, 57, 57, 57, 58'),
    (N'Galactic HQ', N'Commander Saturn', N'Bronzong, Octillery, Alakazam, Rhyperior, Magmortar, Toxicroak', N'56, 56, 56, 56, 56, 57'),
    (N'Mt. Coronet ~ 3F', N'Galactic Grunt', N'Nidorina, Swalot, Persian', N'54, 54, 54'),
    (N'Mt. Coronet ~ 3F', N'Galactic Grunt', N'Nidorino, Drapion, Kricketune', N'54, 54, 54'),
    (N'Mt. Coronet ~ 4F', N'Galactic Grunt', N'Houndoom, Golbat, Beedrill', N'54, 54, 54'),
    (N'Mt. Coronet ~ 4F', N'Galactic Grunt', N'Ledian, Weezing', N'55, 55'),
    (N'Mt. Coronet ~ Tunnel to Route 211 Entrance', N'Galactic Grunt', N'Golbat', N'56'),
    (N'Mt. Coronet ~ Tunnel to Route 211 Entrance', N'Galactic Grunt', N'Murkrow, Mightyena, Sneasel', N'54, 54, 54'),
    (N'Mt. Coronet ~ Tunnel to Route 211 Entrance', N'Galactic Grunt', N'Masquerain, Muk', N'55, 55'),
    (N'Mt. Coronet ~ 6F', N'Galactic Grunt', N'Golbat, Houndoom, Yanmega', N'55, 55, 55'),
    (N'Mt. Coronet ~ 6F', N'Galactic Grunt', N'Ariados, Persian, Forretress', N'55, 55, 55'),
    (N'Mt. Coronet ~ 7F', N'Galactic Grunt', N'Murkrow, Golbat, Toxicroak, Pinsir', N'55, 55, 55, 55'),
    (N'Spear Pillar', N'Galactic Grunt', N'Toxicroak, Venomoth, Golbat', N'56, 56, 56'),
    (N'Spear Pillar', N'Galactic Grunt', N'Persian, Beautifly, Hypno', N'56, 56, 56'),
    (N'Spear Pillar', N'Commander Mars', N'Crobat, Yanmega, Bronzong, Electivire, Kangaskhan, Purugly', N'57, 57, 57, 57, 57, 58'),
    (N'Spear Pillar', N'Commander Jupiter', N'Crobat, Sableye, Bronzong, Tangrowth, Gastrodon, Skuntank', N'57, 57, 57, 57, 57, 58'),
    (N'Spear Pillar', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Arcanine, Torterra', N'58, 58, 58, 58, 58, 59'),
    (N'Spear Pillar', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Breloom, Infernape', N'58, 58, 58, 58, 58, 59'),
    (N'Spear Pillar', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Breloom, Arcanine, Empoleon', N'58, 58, 58, 58, 58, 59'),
    (N'Distortion World', N'Galactic Boss Cyrus', N'Palkia, Dialga', N'70, 70'),
    (N'Distortion World', N'Galactic Boss Cyrus', N'Crobat, Honchkrow, Houndoom, Gyarados, Magnezone, Weavile', N'59, 59, 59, 59, 59, 60'),
    (N'Route 222', N'Rich Boy Trey (!)', N'Luxray, Sceptile, Linoone', N'57, 57, 57'),
    (N'Route 222', N'Beauty Nicola', N'Lopunny, Flareon, Meganium', N'57, 57, 57'),
    (N'Route 222', N'Policeman Thomas', N'Noctowl', N'59'),
    (N'Route 222', N'Sailor Marc (!)', N'Lanturn, Machamp, Mantine', N'57, 57, 57'),
    (N'Route 222', N'Tuber Conner', N'Remoraid, Remoraid', N'57, 57'),
    (N'Route 222', N'Sailor Luther', N'Pelipper, Gastrodon, Poliwrath, Kingler', N'56, 56, 56, 56'),
    (N'Route 222', N'Fisherman Alec (!)', N'Gyarados, Gyarados, Gyarados', N'57, 57, 57'),
    (N'Route 222', N'Fisherman George', N'Octillery, Lumineon', N'58, 58'),
    (N'Route 222', N'Fisherman Brett', N'Qwilfish', N'59'),
    (N'Route 222', N'Fisherman Cole', N'Seaking, Sharpedo, Kingdra', N'57, 57, 57'),
    (N'Route 222', N'Tuber Holly', N'Azumarill', N'58'),
    (N'Route 222', N'Poké Kid Janet', N'Pikachu, Pikachu', N'57, 57'),
    (N'Route 222', N'Rich Boy Trey (C)', N'Luxray, Sceptile, Linoone', N'70, 70, 70'),
    (N'Route 222', N'Rich Boy Trey (S)', N'Luxray, Sceptile, Linoone', N'75, 75, 75'),
    (N'Route 222', N'Sailor Marc (C)', N'Lanturn, Machamp, Mantine', N'70, 70, 70'),
    (N'Route 222', N'Sailor Marc (S)', N'Lanturn, Machamp, Mantine', N'75, 75, 75'),
    (N'Route 222', N'Fisherman Alec (C)', N'Gyarados, Gyarados, Gyarados', N'70, 70, 70'),
    (N'Sunyshore City', N'Arcade Star Dahlia', N'Blaziken, Dusknoir, Medicham, Togekiss, Ludicolo, Zapdos', N'63, 63, 63, 63, 63, 63'),
    (N'Sunyshore Gym', N'School Kid Tiera', N'Plusle, Minun, Pachirisu', N'56, 56, 59'),
    (N'Sunyshore Gym', N'School Kid Forrest', N'Elekid, Elekid, Electabuzz', N'56, 56, 59'),
    (N'Sunyshore Gym', N'Guitarist Jerry', N'Electabuzz, Luxray', N'60, 60'),
    (N'Sunyshore Gym', N'Poké Kid Meghan', N'Pichu, Pichu, Pikachu', N'56, 56, 59'),
    (N'Sunyshore Gym', N'Ace Trainer Destiny', N'Raichu, Lanturn, Jolteon, Luxray', N'60, 60, 60, 60'),
    (N'Sunyshore Gym', N'Guitarist Preston', N'Electabuzz, Magnezone', N'60, 60'),
    (N'Sunyshore Gym', N'Guitarist Lonnie', N'Electabuzz, Electrode', N'60, 60'),
    (N'Sunyshore Gym', N'Ace Trainer Zachery', N'Ampharos, Magnezone, Manectric, Electrode', N'60, 60, 60, 60'),
    (N'Sunyshore Gym', N'Leader Volkner', N'Jolteon, Raichu, Rotom, Rotom, Luxray, Electivire', N'61, 61, 61, 61, 61, 62'),
    (N'Route 223', N'Swimmer Wesley (!)', N'Floatzel, Sharpedo, Qwilfish', N'59, 59, 59'),
    (N'Route 223', N'Swimmer Ricardo', N'Tentacruel', N'61'),
    (N'Route 223', N'Swimmer Francisco (!)', N'Ludicolo, Relicanth, Poliwrath', N'59, 59, 59'),
    (N'Route 223', N'Swimmer Colton', N'Pelipper, Octillery, Feraligatr', N'59, 59, 59'),
    (N'Route 223', N'Swimmer Troy', N'Gyarados', N'61'),
    (N'Route 223', N'Swimmer Oscar', N'Mantine, Blastoise, Whiscash', N'59, 59, 59'),
    (N'Route 223', N'Swimmer Miranda (!)', N'Cloyster, Lumineon', N'60, 60'),
    (N'Route 223', N'Swimmer Aubree', N'Bibarel, Quagsire', N'60, 60'),
    (N'Route 223', N'Swimmer Paige', N'Azumarill, Slowbro, Gorebyss', N'59, 59, 59'),
    (N'Route 223', N'Swimmer Crystal (!)', N'Wailord, Seaking, Corsola', N'59, 59, 59'),
    (N'Route 223', N'Swimmer Cassandra', N'Vaporeon', N'61'),
    (N'Route 223', N'Swimmer Gabrielle', N'Golduck, Lapras, Starmie', N'59, 59, 59'),
    (N'Route 223', N'Sailor Zachariah (!)', N'Kingler, Machamp, Gastrodon, Slowking', N'58, 58, 58, 58'),
    (N'Route 223', N'Swimmer Wesley (S)', N'Floatzel, Sharpedo, Qwilfish', N'75, 75, 75'),
    (N'Route 223', N'Swimmer Francisco (S)', N'Ludicolo, Relicanth, Poliwrath', N'75, 75, 75'),
    (N'Route 223', N'Swimmer Miranda (S)', N'Cloyster, Lumineon, Starmie', N'75, 75, 75'),
    (N'Route 223', N'Swimmer Crystal (S)', N'Wailord, Seaking, Corsola', N'75, 75, 75'),
    (N'Route 223', N'Sailor Zachariah (S)', N'Kingler, Machamp, Gastrodon, Slowking', N'74, 74, 74, 74'),
    (N'Victory Road', N'Psychic Bryce', N'Gengar, Gardevoir, Exeggutor, Espeon', N'63, 63, 63, 63'),
    (N'Victory Road', N'Bird Keeper Hana', N'Noctowl, Dodrio, Farfetch''d, Pidgeot', N'63, 63, 63, 63'),
    (N'Victory Road', N'Ace Trainer Mariah', N'Blissey, Walrein, Aggron, Jumpluff, Mismagius', N'63, 63, 63, 63, 63'),
    (N'Victory Road', N'Ace Trainer Omar', N'Rapidash, Tropius, Rampardos, Heracross, Mamoswine', N'63, 63, 63, 63, 63'),
    (N'Victory Road', N'Ace Trainer Sydney', N'Clefable, Torterra, Starmie, Magcargo, Tauros', N'63, 63, 63, 63, 63'),
    (N'Victory Road', N'Veteran Clayton', N'Lickilicky, Hippowdon, Staraptor, Pinsir, Electivire', N'64, 64, 64, 64, 64'),
    (N'Victory Road', N'Double Team Al & Kay', N'Whiscash, Ambipom, Umbreon, Venusaur', N'64, 64, 64, 64'),
    (N'Victory Road', N'Black Belt Miles', N'Machamp, Poliwrath, Hitmonchan, Hitmonlee', N'63, 63, 63, 63'),
    (N'Victory Road', N'Psychic Valencia', N'Chimecho, Dusknoir, Absol, Grumpig', N'63, 63, 63, 63'),
    (N'Victory Road', N'Double Team Jo & Pat', N'Medicham, Milotic, Ninetales, Victreebel', N'64, 64, 64, 64'),
    (N'Victory Road', N'Ace Trainer Henry', N'Honchkrow, Marowak, Carnivine, Manectric, Slowking', N'63, 63, 63, 63, 63'),
    (N'Victory Road', N'Dragon Tamer Ondrej', N'Kingdra, Altaria, Salamence, Charizard', N'64, 64, 64, 64'),
    (N'Victory Road', N'Veteran Edgar', N'Porygon-Z, Tangrowth, Empoleon, Golem, Typhlosion', N'64, 64, 64, 64, 64'),
    (N'Victory Road', N'Dragon Tamer Clinton', N'Flygon, Gyarados, Dragonite, Aerodactyl', N'64, 64, 64, 64'),
    (N'Victory Road ~ East', N'PKMN Trainer Marley', N'Starmie, Electrode, Sceptile, Crobat, Weavile, Arcanine', N'65, 65, 65, 65, 65, 66'),
    (N'Victory Road ~ East', N'Ace Trainer Micah', N'Metagross, Ludicolo, Blaziken', N'65, 65, 65'),
    (N'Victory Road ~ East', N'Ace Trainer Brandi', N'Nidoqueen, Kangaskhan, Jynx', N'65, 65, 65'),
    (N'Victory Road ~ East', N'Psychic Desiree', N'Mr. Mime, Drifblim, Hypno', N'64, 64, 64'),
    (N'Victory Road ~ East', N'Psychic Landon', N'Banette, Alakazam, Girafarig', N'64, 64, 64'),
    (N'Victory Road ~ East', N'Black Belt Eddie', N'Primeape, Breloom, Infernape', N'64, 64, 64'),
    (N'Victory Road ~ East', N'Veteran Terrell', N'Parasect, Quagsire, Houndoom', N'66, 66, 66'),
    (N'Victory Road ~ East', N'Dragon Tamer Joe', N'Dragonair, Salamence, Kingdra', N'65, 65, 65'),
    (N'Victory Road ~ East', N'Bird Keeper Autumn', N'Xatu, Pelipper, Delibird', N'64, 64, 64'),
    (N'Victory Road ~ East', N'Psychic Deandre', N'Dusclops, Sableye, Dusknoir', N'64, 64, 64'),
    (N'Victory Road ~ East', N'Psychic Kendra', N'Chimecho, Froslass, Wobbuffet', N'64, 64, 64'),
    (N'Victory Road ~ East', N'Black Belt Willie', N'Heracross, Machamp, Toxicroak', N'64, 64, 64'),
    (N'Victory Road ~ East', N'Veteran Brenden', N'Forretress, Kabutops, Donphan', N'66, 66, 66'),
    (N'Victory Road ~ East', N'Ace Trainer Arthur', N'Gastrodon, Beedrill, Ampharos', N'64, 64, 64'),
    (N'Victory Road ~ East', N'Ace Trainer Clarice', N'Swalot, Ninetales, Scizor', N'64, 64, 64'),
    (N'Route 224', N'Ace Trainer Ruben', N'Shiftry, Gyarados, Politoed, Leafeon', N'67, 67, 67, 67'),
    (N'Route 224', N'Psychic Brittney', N'Hypno, Alakazam, Medicham, Lunatone', N'66, 66, 66, 66'),
    (N'Route 224', N'Psychic Maxwell', N'Mismagius, Gengar, Slowbro, Solrock', N'66, 66, 66, 66'),
    (N'Route 224', N'Veteran Armando (!)', N'Muk, Mightyena, Lickilicky, Pelipper', N'68, 68, 68, 68'),
    (N'Route 224', N'Black Belt Carl', N'Hariyama, Hitmonlee, Hitmonchan, Hitmontop', N'66, 66, 66, 66'),
    (N'Route 224', N'Ruin Maniac Larry', N'Aerodactyl, Armaldo, Cradily, Relicanth', N'66, 66, 66, 66'),
    (N'Route 224', N'Ace Trainer Jamie', N'Vaporeon, Metagross, Roserade, Dugtrio', N'67, 67, 67, 67'),
    (N'Route 224', N'Dragon Tamer Hayden (!)', N'Altaria, Salamence, Kingdra, Dragonite', N'67, 67, 67, 67'),
    (N'Route 224', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Vaporeon, Torterra', N'69, 69, 69, 69, 69, 70'),
    (N'Route 224', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Jolteon, Infernape', N'69, 69, 69, 69, 69, 70'),
    (N'Route 224', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Flareon, Empoleon', N'69, 69, 69, 69, 69, 70'),
    (N'Route 224', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Vaporeon, Torterra', N'69, 69, 69, 69, 69, 70'),
    (N'Route 224', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Jolteon, Infernape', N'69, 69, 69, 69, 69, 70'),
    (N'Route 224', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Flareon, Empoleon', N'69, 69, 69, 69, 69, 70'),
    (N'Route 224', N'Veteran Armando (S)', N'Muk, Mightyena, Lickilicky, Pelipper', N'77, 77, 77, 77'),
    (N'Route 224', N'Dragon Tamer Hayden (S)', N'Altaria, Salamence, Kingdra, Dragonite', N'77, 77, 77, 77'),
    (N'Pokémon League', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Arcanine, Torterra', N'70, 70, 70, 70, 70, 71'),
    (N'Pokémon League', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Breloom, Infernape', N'70, 70, 70, 70, 70, 71'),
    (N'Pokémon League', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Breloom, Arcanine, Empoleon', N'70, 70, 70, 70, 70, 71'),
    (N'Pokémon League', N'Elite Four Aaron', N'Yanmega, Scizor, Heracross, Vespiquen, Armaldo, Drapion', N'71, 71, 71, 71, 71, 72'),
    (N'Pokémon League', N'Elite Four Aaron', N'Venomoth, Scyther, Pinsir, Forretress, Armaldo, Drapion', N'71, 71, 71, 71, 71, 72'),
    (N'Pokémon League', N'Elite Four Aaron', N'Masquerain, Beautifly, Heracross, Scizor, Dustox, Drapion', N'71, 71, 71, 71, 71, 72'),
    (N'Pokémon League', N'Elite Four Aaron', N'Scyther, Yanmega, Pinsir, Scizor, Flygon, Drapion', N'71, 71, 71, 71, 71, 72'),
    (N'Pokémon League', N'Elite Four Bertha', N'Hippowdon, Whiscash, Gliscor, Golem, Donphan, Rhyperior', N'72, 72, 72, 72, 72, 73'),
    (N'Pokémon League', N'Elite Four Bertha', N'Hippowdon, Sudowoodo, Gliscor, Torterra, Camerupt, Rhyperior', N'72, 72, 72, 72, 72, 73'),
    (N'Pokémon League', N'Elite Four Bertha', N'Tyranitar, Swampert, Dugtrio, Mamoswine, Claydol, Rhyperior', N'72, 72, 72, 72, 72, 73'),
    (N'Pokémon League', N'Elite Four Bertha', N'Tyranitar, Quagsire, Mamoswine, Dugtrio, Torterra, Rhyperior', N'72, 72, 72, 72, 72, 73'),
    (N'Pokémon League', N'Elite Four Flint', N'Ninetales, Houndoom, Flareon, Rapidash, Infernape, Magmortar', N'73, 73, 73, 73, 73, 74'),
    (N'Pokémon League', N'Elite Four Flint', N'Rapidash, Lopunny, Drifblim, Steelix, Infernape, Magmortar', N'73, 73, 73, 73, 73, 74'),
    (N'Pokémon League', N'Elite Four Flint', N'Ninetales, Arcanine, Magcargo, Lopunny, Charizard, Magmortar', N'73, 73, 73, 73, 73, 74'),
    (N'Pokémon League', N'Elite Four Flint', N'Torkoal, Houndoom, Arcanine, Drifblim, Typhlosion, Magmortar', N'73, 73, 73, 73, 73, 74'),
    (N'Pokémon League', N'Elite Four Lucian', N'Mr. Mime, Espeon, Bronzong, Alakazam, Metagross, Gallade', N'74, 74, 74, 74, 74, 75'),
    (N'Pokémon League', N'Elite Four Lucian', N'Espeon, Girafarig, Medicham, Starmie, Exeggutor, Gallade', N'74, 74, 74, 74, 74, 75'),
    (N'Pokémon League', N'Elite Four Lucian', N'Hypno, Slowbro, Gardevoir, Jynx, Bronzong, Gallade', N'74, 74, 74, 74, 74, 75'),
    (N'Pokémon League', N'Elite Four Lucian', N'Alakazam, Gardevoir, Exeggutor, Starmie, Metagross, Gallade', N'74, 74, 74, 74, 74, 75'),
    (N'Pokémon League', N'Champion Cynthia', N'Spiritomb, Roserade, Togekiss, Lucario, Milotic, Garchomp', N'77, 77, 77, 77, 77, 78'),
    (N'Pokémon League', N'Champion Cynthia', N'Milotic, Spiritomb, Ampharos, Staraptor, Lucario, Garchomp', N'77, 77, 77, 77, 77, 78'),
    (N'Pokémon League', N'Champion Cynthia', N'Togekiss, Milotic, Spiritomb, Lucario, Glaceon, Garchomp', N'77, 77, 77, 77, 77, 78'),
    (N'Pokémon League', N'Champion Cynthia', N'Clefable, Roserade, Mismagius, Lopunny, Milotic, Garchomp', N'77, 77, 77, 77, 77, 78'),
    (N'Pokémon League', N'Elite Four Aaron', N'Yanmega, Scizor, Heracross, Scyther, Armaldo, Drapion', N'83, 83, 83, 83, 83, 84'),
    (N'Pokémon League', N'Elite Four Bertha', N'Hippowdown, Swampert, Gliscor, Tyranitar, Dugtrio, Rhyperior', N'84, 84, 84, 84, 84, 85'),
    (N'Pokémon League', N'Elite Four Flint', N'Ninetales, Houndoom, Magmortar, Infernape, Rapidash, Moltres', N'85, 85, 85, 85, 85, 86'),
    (N'Pokémon League', N'Elite Four Lucian', N'Mr. Mime, Espeon, Gallade, Metagross, Alakazam, Latios', N'86, 86, 86, 86, 86, 87'),
    (N'Pokémon League', N'Champion Cynthia', N'Spiritomb, Togekiss, Lucario, Garchomp, Milotic, Rayquaza', N'88, 88, 88, 88, 88, 89'),
    (N'Fight Area', N'Leader Volkner', N'Raichu, Jolteon, Electivire', N'74, 74, 75'),
    (N'Fight Area', N'Elite Four Flint', N'Arcanine, Flareon, Magmortar', N'74, 74, 75'),
    (N'Fight Area', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Arcanine, Torterra', N'74, 74, 74, 74, 74, 75'),
    (N'Fight Area', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Breloom, Infernape', N'74, 74, 74, 74, 74, 75'),
    (N'Fight Area', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Breloom, Arcanine, Empoleon', N'74, 74, 74, 74, 74, 75'),
    (N'Route 225', N'Ace Trainer Rodolfo (!)', N'Starmie, Scizor, Sceptile, Ninetales', N'73, 73, 73, 73'),
    (N'Route 225', N'PKMN Ranger Ashlee (!)', N'Linoone, Arbok, Butterfree', N'73, 73, 73'),
    (N'Route 225', N'Bird Keeper Audrey (!)', N'Farfetch''d, Swellow, Pidgeot', N'73, 73, 73'),
    (N'Route 225', N'Psychic Daisy (!)', N'Slowbro, Slowking', N'74, 74'),
    (N'Route 225', N'Dragon Tamer Geoffrey (!)', N'Altaria', N'75'),
    (N'Route 225', N'Ace Trainer Deanna (!)', N'Ampharos, Tropius, Lapras, Miltank', N'73, 73, 73, 73'),
    (N'Route 225', N'PKMN Ranger Dwayne', N'Skarmory, Golduck, Donphan', N'73, 73, 73'),
    (N'Route 225', N'Ace Trainer Quinn', N'Pinsir, Lanturn, Golem, Exploud', N'73, 73, 73, 73'),
    (N'Route 225', N'Ace Trainer Heather *', N'Pelipper, Togekiss, Aerodactyl, Pidgeot, Tropius, Dragonite', N'76, 76, 76, 76, 76, 77'),
    (N'Route 225', N'Ace Trainer Rodolfo (S)', N'Starmie, Scizor, Sceptile, Ninetales', N'79, 79, 79, 79'),
    (N'Route 225', N'PKMN Ranger Ashlee (S)', N'Linoone, Arbok, Butterfree', N'78, 78, 78'),
    (N'Route 225', N'Bird Keeper Audrey (S)', N'Farfetch''d, Swellow, Pidgeot', N'78, 78, 78'),
    (N'Route 225', N'Psychic Daisy (S)', N'Slowbro, Slowking', N'79, 79'),
    (N'Route 225', N'Dragon Tamer Geoffrey (S)', N'Altaria, Garchomp', N'79, 79'),
    (N'Route 225', N'Ace Trainer Deanna (S)', N'Ampharos, Tropius, Lapras, Miltank', N'79, 79, 79, 79'),
    (N'Route 226', N'Swimmer Lydia', N'Azumarill, Dewgong, Wailord', N'73, 73, 73'),
    (N'Route 226', N'Ace Trainer Graham', N'Tyrogue, Hitmonchan, Hitmonlee, Hitmontop', N'74, 74, 74, 74'),
    (N'Route 226', N'Bird Keeper Geneva', N'Fearow, Xatu, Swellow', N'74, 74, 74'),
    (N'Route 226', N'Dragon Tamer Stanley', N'Kingdra', N'76'),
    (N'Route 226', N'Swimmer Wade', N'Sharpedo, Whiscash', N'74, 74'),
    (N'Route 226', N'Ace Trainer Wyver *', N'Kingdra, Flygon, Altaria, Dragonite, Garchomp, Salamence', N'76, 76, 76, 76, 76, 77'),
    (N'Route 227', N'Ace Trainer Saul (!)', N'Tauros', N'78'),
    (N'Route 227', N'PKMN Ranger Felicia', N'Jumpluff, Lopunny', N'76, 76'),
    (N'Route 227', N'Black Belt Griffin', N'Breloom, Medicham, Lucario', N'75, 75, 75'),
    (N'Route 227', N'Ace Trainer Mikayla', N'Seviper, Persian, Absol', N'76, 76, 76'),
    (N'Route 227', N'Ace Trainer Slythe *', N'Gengar, Tentacruel, Nidoqueen, Crobat, Toxicroak, Vileplume', N'76, 76, 76, 76, 76, 77'),
    (N'Route 227', N'PKMN Trainer Buck', N'Torkoal, Shuckle, Umbreon, Dusknoir, Cloyster, Claydol', N'77, 77, 77, 77, 77, 78'),
    (N'Route 227', N'Ace Trainer Saul (S)', N'Tauros', N'80'),
    (N'Route 228', N'Ace Trainer Jose', N'Floatzel, Sandslash, Manectric', N'76, 76, 76'),
    (N'Route 228', N'Ace Trainer Moira (!)', N'Cacturne, Gastrodon, Claydol', N'76, 76, 76'),
    (N'Route 228', N'PKMN Ranger Kyler (!)', N'Exeggutor, Zangoose, Empoleon', N'75, 75, 75'),
    (N'Route 228', N'PKMN Ranger Krista', N'Marowak, Aggron', N'76, 76'),
    (N'Route 228', N'Dragon Tamer Keegan', N'Flygon', N'76'),
    (N'Route 228', N'Psychic Corbin (!)', N'Hypno, Gallade', N'76, 76'),
    (N'Route 228', N'Ace Trainer Meagan', N'Delcatty, Abomasnow', N'77, 77'),
    (N'Route 228', N'Black Belt Davon (!)', N'Hariyama, Machamp, Primeape', N'75, 75, 75'),
    (N'Route 228', N'Ace Trainer Shade *', N'Houndoom, Weavile, Shiftry, Sharpedo, Spiritomb, Tyranitar', N'76, 76, 76, 76, 76, 77'),
    (N'Route 228', N'Ace Trainer Moira (S)', N'Cacturne, Gastrodon, Claydol', N'79, 79, 79'),
    (N'Route 228', N'PKMN Ranger Kyler (S)', N'Exeggutor, Zangoose, Empoleon', N'78, 78, 78'),
    (N'Route 228', N'Psychic Corbin (S)', N'Hypno, Gallade, Xatu', N'78, 78, 78'),
    (N'Route 228', N'Black Belt Davon (S)', N'Hariyama, Machamp, Primeape', N'78, 78, 78'),
    (N'Route 229', N'PKMN Ranger Deshawn', N'Spinda, Kecleon, Granbull', N'74, 74, 74'),
    (N'Route 229', N'Ace Trainer Felix', N'Dusknoir, Salamence', N'76, 76'),
    (N'Route 229', N'Ace Trainer Dana', N'Mightyena, Gardevoir, Butterfree', N'75, 75, 75'),
    (N'Route 229', N'Ace Trainer Sandra', N'Dugtrio, Raichu, Arcanine, Vileplume', N'74, 74, 74, 74'),
    (N'Route 229', N'Ace Trainer Gene *', N'Stantler, Dodrio, Girafarig, Bibarel, Porygon-Z, Snorlax', N'76, 76, 76, 76, 76, 77'),
    (N'Route 230', N'Swimmer Glenn (!)', N'Octillery, Politoed', N'73, 73'),
    (N'Route 230', N'Swimmer Joanna (!)', N'Luvdisc, Corsola, Vaporeon', N'72, 72, 72'),
    (N'Route 230', N'Swimmer Kurt', N'Krabby, Corphish, Kingler, Crawdaunt', N'70, 70, 72, 72'),
    (N'Route 230', N'Swimmer Sophia', N'Delibird, Mantine', N'73, 73'),
    (N'Route 230', N'Swimmer Sam', N'Walrein, Gastrodon, Seaking', N'72, 72, 72'),
    (N'Route 230', N'Swimmer Mallory', N'Masquerain, Ludicolo', N'73, 73'),
    (N'Route 230', N'Ace Trainer Luna *', N'Wigglytuff, Clefable, Azumarill, Granbull, Mawile, Gardevoir', N'76, 76, 76, 76, 76, 77'),
    (N'Route 230', N'Swimmer Glenn (S)', N'Octillery, Politoed', N'76, 76'),
    (N'Route 230', N'Swimmer Joanna (S)', N'Luvdisc, Corsola, Vaporeon', N'75, 75, 75'),
    (N'Stark Mountain ~ Outside', N'Dragon Tamer Darien', N'Dragonite', N'78'),
    (N'Stark Mountain ~ Entrance', N'Commander Mars', N'Crobat, Yanmega, Bronzong, Electivire, Kangaskhan, Purugly', N'77, 77, 77, 77, 77, 78'),
    (N'Stark Mountain ~ Entrance', N'Commander Jupiter', N'Bronzong, Sableye, Crobat, Tangrowth, Gastrodon, Skuntank', N'77, 77, 77, 77, 77, 78'),
    (N'Stark Mountain ~ Interior', N'Ace Trainer Keenan', N'Primeape, Banette, Electivire', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Ace Trainer Kassandra', N'Jumpluff, Ampharos, Steelix', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Ace Trainer Stefan', N'Tyranitar, Torterra, Aggron', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Ace Trainer Jasmin', N'Drapion, Hippowdown, Magmortar', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Bird Keeper Krystal', N'Staraptor, Fearow, Noctowl', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Black Belt Ray', N'Breloom, Toxicroak, Hariyama', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Ace Trainer Abel', N'Glalie, Crobat, Ninetales', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Ace Trainer Monique', N'Luxray, Ursaring, Gliscor', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Psychic Chelsey', N'Lunatone, Gardevoir, Xatu', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Psychic Sterling', N'Solrock, Gallade, Claydol', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Veteran Harlan', N'Raticate, Drifblim, Shiftry', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Dragon Tamer Kenny', N'Salamence, Flygon, Altaria', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Ace Trainer Skylar', N'Exploud, Rampardos, Pelipper', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Ace Trainer Natasha', N'Wigglytuff, Alakazam, Medicham', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Dragon Tamer Drake', N'Garchomp, Dragonite, Kingdra', N'78, 78, 78'),
    (N'Stark Mountain ~ Interior', N'Black Belt Jarrett', N'Machamp, Blaziken, Poliwrath', N'78, 78, 78'),
    (N'Battleground', N'Leader Roark', N'Sudowoodo, Probopass, Golem, Aerodactyl, Tyranitar, Rampardos', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Leader Gardenia', N'Cherrim, Tangrowth, Bellossom, Torterra, Breloom, Roserade', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Leader Fantina', N'Drifblim, Dusknoir, Banette, Spiritomb, Gengar, Mismagius', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Leader Maylene', N'Medicham, Machamp, Infernape, Toxicroak, Gallade, Lucario', N'82, 82, 82, 82, 82, 83'),
    (N'Battleground', N'Leader Wake', N'Quagsire, Gyarados, Poliwrath, Ludicolo, Sharpedo, Floatzel', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Leader Byron', N'Bronzong, Magnezone, Steelix, Forretress, Aggron, Bastiodon', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Leader Candice', N'Abomasnow, Weavile, Glaceon, Walrein, Mamoswine, Froslass', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Leader Volkner', N'Jolteon, Raichu, Rotom, Rotom, Luxray, Electivire', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'PKMN Trainer Cheryl', N'Wobbuffet, Snorlax, Drifblim, Hariyama, Wailord, Blissey', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'PKMN Trainer Mira', N'Togekiss, Gengar, Exeggutor, Magnezone, Porygon-Z, Alakazam', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'PKMN Trainer Riley', N'Absol, Ursaring, Metagross, Salamence, Slaking, Lucario', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'PKMN Trainer Marley', N'Starmie, Electrode, Sceptile, Crobat, Weavile, Arcanine', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'PKMN Trainer Buck', N'Torkoal, Shuckle, Umbreon, Dusknoir, Cloyster, Claydol', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Arcanine, Torterra', N'84, 84, 84, 84, 84, 85'),
    (N'Battleground', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Azumarill, Breloom, Infernape', N'84, 84, 84, 84, 84, 85'),
    (N'Battleground', N'PKMN Trainer Barry', N'Staraptor, Heracross, Snorlax, Breloom, Arcanine, Empoleon', N'84, 84, 84, 84, 84, 85'),
    (N'Battleground', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Vaporeon, Torterra', N'83, 83, 83, 83, 83, 84'),
    (N'Battleground', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Jolteon, Infernape', N'83, 83, 83, 83, 83, 84'),
    (N'Battleground', N'PKMN Trainer Dawn', N'Alakazam, Mamoswine, Clefable, Lopunny, Flareon, Empoleon', N'83, 83, 83, 83, 83, 84'),
    (N'Battleground', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Vaporeon, Torterra', N'83, 83, 83, 83, 83, 84'),
    (N'Battleground', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Jolteon, Infernape', N'83, 83, 83, 83, 83, 84'),
    (N'Battleground', N'PKMN Trainer Lucas', N'Alakazam, Mamoswine, Granbull, Lickilicky, Flareon, Empoleon', N'83, 83, 83, 83, 83, 84'),
    (N'Battleground', N'Commander Mars', N'Crobat, Yanmega, Bronzong, Electivire, Kangaskhan, Purugly', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Commander Jupiter', N'Bronzong, Sableye, Crobat, Tangrowth, Gastrodon, Skuntank', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Commander Saturn', N'Bronzong, Octillery, Alakazam, Rhyperior, Magmortar, Toxicroak', N'81, 81, 81, 81, 81, 82'),
    (N'Battleground', N'Galactic Boss Cyrus', N'Crobat, Honchkrow, Houndoom, Gyarados, Magnezone, Weavile', N'83, 83, 83, 83, 83, 84'),
    (N'Pokémon Center', N'Reporter Kinsey', N'Drifloon, Shinx', N'10, 10'),
    (N'Pokémon Center', N'Reporter Kinsey (3)', N'Drifloon, Luxio', N'30, 30'),
    (N'Pokémon Center', N'Reporter Kinsey (5)', N'Drifblim, Luxray', N'40, 40'),
    (N'Pokémon Center', N'Reporter Kinsey (8)', N'Drifblim, Luxray', N'60, 60'),
    (N'Pokémon Center', N'Reporter Kinsey (C)', N'Drifblim, Luxray', N'70, 70'),
    (N'Pokémon Center', N'Reporter Kinsey (S)', N'Drifblim, Luxray', N'80, 80'),
    (N'Pokémon Center', N'Cameraman Tevin', N'Mime Jr., Machop', N'10, 10'),
    (N'Pokémon Center', N'Cameraman Tevin (3)', N'Mime Jr., Machoke', N'30, 30'),
    (N'Pokémon Center', N'Cameraman Tevin (5)', N'Mr. Mime, Machamp', N'40, 40'),
    (N'Pokémon Center', N'Cameraman Tevin (8)', N'Mr. Mime, Machamp', N'60, 60'),
    (N'Pokémon Center', N'Cameraman Tevin (C)', N'Mr. Mime, Machamp', N'70, 70'),
    (N'Pokémon Center', N'Cameraman Tevin (S)', N'Mr. Mime, Machamp', N'80, 80'),
    (N'Pokémon Center', N'Interviewers Roxy & Oli', N'Magnemite, Ralts', N'10, 10'),
    (N'Pokémon Center', N'Interviewers Roxy & Oli (3)', N'Magneton, Kirlia', N'30, 30'),
    (N'Pokémon Center', N'Interviewers Roxy & Oli (5)', N'Magnezone, Gardevoir', N'40, 40'),
    (N'Pokémon Center', N'Interviewers Roxy & Oli (8)', N'Magnezone, Gardevoir', N'60, 60'),
    (N'Pokémon Center', N'Interviewers Roxy & Oli (C)', N'Magnezone, Gardevoir', N'70, 70'),
    (N'Pokémon Center', N'Interviewers Roxy & Oli (S)', N'Magnezone, Gardevoir', N'80, 80'),
    (N'Pokémon Center', N'Idol Grace', N'Igglybuff, Cleffa', N'10, 10'),
    (N'Pokémon Center', N'Idol Grace (3)', N'Jigglypuff, Clefairy', N'30, 30'),
    (N'Pokémon Center', N'Idol Grace (5)', N'Wigglytuff, Clefable', N'40, 40'),
    (N'Pokémon Center', N'Idol Grace (8)', N'Wigglytuff, Clefable', N'60, 60'),
    (N'Pokémon Center', N'Idol Grace (C)', N'Wigglytuff, Clefable', N'70, 70'),
    (N'Pokémon Center', N'Idol Grace (S)', N'Wigglytuff, Clefable', N'80, 80'),
    (N'Pokémon Center', N'Guitarist Arturo', N'Kricketot, Voltorb', N'10, 10'),
    (N'Pokémon Center', N'Guitarist Arturo (3)', N'Kricketune, Electrode', N'30, 30'),
    (N'Pokémon Center', N'Guitarist Arturo (5)', N'Kricketune, Electrode', N'40, 40'),
    (N'Pokémon Center', N'Guitarist Arturo (8)', N'Kricketune, Electrode', N'60, 60'),
    (N'Pokémon Center', N'Guitarist Arturo (C)', N'Kricketune, Electrode', N'70, 70'),
    (N'Pokémon Center', N'Guitarist Arturo (S)', N'Kricketune, Electrode', N'80, 80'),
    (N'Pokémon Center', N'Poké Kid Ariel', N'Pichu, Pichu, Pichu', N'10, 10, 10'),
    (N'Pokémon Center', N'Poké Kid Ariel (3)', N'Pichu, Pikachu, Pikachu', N'30, 30, 30'),
    (N'Pokémon Center', N'Poké Kid Ariel (5)', N'Pichu, Pikachu, Raichu', N'40, 40, 40'),
    (N'Pokémon Center', N'Poké Kid Ariel (8)', N'Pichu, Pikachu, Raichu', N'60, 60, 60'),
    (N'Pokémon Center', N'Poké Kid Ariel (C)', N'Pichu, Pikachu, Raichu', N'70, 70, 70'),
    (N'Pokémon Center', N'Poké Kid Ariel (S)', N'Pichu, Pikachu, Raichu', N'80, 80, 80'),
    (N'Pokémon Center', N'Clown Lee', N'Aipom, Abra', N'10, 10'),
    (N'Pokémon Center', N'Clown Lee (3)', N'Aipom, Kadabra', N'30, 30'),
    (N'Pokémon Center', N'Clown Lee (5)', N'Ambipom, Alakazam', N'40, 40'),
    (N'Pokémon Center', N'Clown Lee (8)', N'Ambipom, Alakazam', N'60, 60'),
    (N'Pokémon Center', N'Clown Lee (C)', N'Ambipom, Alakazam', N'70, 70'),
    (N'Pokémon Center', N'Clown Lee (S)', N'Ambipom, Alakazam', N'80, 80');
